#pragma once
#include "fates/battle/battle_runtime.hpp"
namespace fates::decomp_detail {
void BattleUnitDeleteHair(BattleUnit& self);
void BattleUnitDeleteHead(BattleUnit& self);
void BattleUnitSetVisible(BattleUnit& self, int a0, bool a1);
void BattleUnitConfrontDir(BattleUnit& self);
void BattleUnitCreateMagic(BattleUnit& self, const char* a0, int a1);
void BattleUnitParticleMan(BattleUnit& self, const char* a0);
void BattleUnitResetOnSkip(BattleUnit& self);
void BattleUnitWaitLoading(BattleUnit& self);
void BattleUnitCreateEffect(BattleUnit& self, const char* a0, const nn::math::MTX34* a1, int a2);
void BattleUnitPlayFootStep(BattleUnit& self, const char* a0);
void BattleUnitPlayWinVoice(BattleUnit& self, const BattlePhase* a0);
void BattleUnitSetTargetDir(BattleUnit& self, const nn::math::VEC3& a0);
void BattleUnitSetTimeSpace(BattleUnit& self, TimeSpace::Type a0);
void BattleUnitUpdateTarget(BattleUnit& self, const nn::math::VEC3& a0);
const nn::math::MTX34* BattleUnitFindBoneMtxPtr(BattleUnit& self, const char* a0);
void BattleUnitPlayDeathVoice(BattleUnit& self);
void BattleUnitPlayMaterialSE(BattleUnit& self, const char* a0);
void BattleUnitPlayThankVoice(BattleUnit& self);
void BattleUnitSetMagicMissed(BattleUnit& self);
void BattleUnitTick_PreUpdate(BattleUnit& self);
void BattleUnitPlayDamageVoice(BattleUnit& self, const BattlePhase* a0);
void BattleUnitTick_PostUpdate(BattleUnit& self);
void BattleUnitCreateColorFader5(BattleUnit& self, int a0, int a1, int a2, int a3, int a4);
void BattleUnitCreateColorFader6(BattleUnit& self, int a0, int a1, int a2, int a3, int a4, int a5);
void BattleUnitSetLocalTimeRate(BattleUnit& self, float a0);
void BattleUnitCreateChantEffect(BattleUnit& self);
void BattleUnitExitSegmentRepeat(BattleUnit& self, bool a0);
AnimObj* BattleUnitGetPrimaryAnimObj(BattleUnit& self);
void BattleUnitCreateShutterFader(BattleUnit& self, float a0, float a1, float a2);
void BattleUnitCreateStealthFader(BattleUnit& self, float a0, float a1, float a2);
void BattleUnitSetInitialLocation(BattleUnit& self, const nn::math::VEC3& a0, const nn::math::VEC3& a1);
void BattleUnitSetMaterialEmotion(BattleUnit& self, int a0);
void BattleUnitSetOpMatVisibility(BattleUnit& self, bool a0);
void BattleUnitSetVisibleFromView(BattleUnit& self, int a0, bool a1);
void BattleUnitTick_SignalExecute(BattleUnit& self);
void BattleUnitAttachShopAccessory(BattleUnit& self, int a0);
void BattleUnitDeleteBodyColliders(BattleUnit& self);
void BattleUnitDetachShopAccessory(BattleUnit& self, int a0, int a1);
void BattleUnitSetInitialDirection(BattleUnit& self);
void BattleUnitSetMaterialAddColor(BattleUnit& self, const nw::ut::Color8& a0);
void BattleUnitSetWeaponVisibility(BattleUnit& self, bool a0);
void BattleUnitUpdateTargetToEnemy(BattleUnit& self);
void BattleUnitCreateFootStepEffect(BattleUnit& self, const char* a0);
void BattleUnitSetMaterialHairColor(BattleUnit& self, const nw::ut::Color8& a0);
void BattleUnitSetMaterialMultColor(BattleUnit& self, const Color8& a0);
void BattleUnitSetMaterialSkinColor(BattleUnit& self, const nw::ut::Color8& a0);
void BattleUnitChangeMagicTargetSide(BattleUnit& self, int a0);
void BattleUnitCreateClothSimulation(BattleUnit& self);
void BattleUnitDeleteClothSimulation(BattleUnit& self);
AnimObj* BattleUnitGetPrimaryRideAnimObj(BattleUnit& self);
void BattleUnitReplaceBodyToSwimwear(BattleUnit& self);
void BattleUnitSetMaterialClothDamage(BattleUnit& self, int a0);
void BattleUnitSetMaterialEyePosition(BattleUnit& self, const nn::math::VEC2& a0);
void BattleUnitCalcRootAnimDisplacement(BattleUnit& self, float& a0, float& a1, float& a2);
void BattleUnitCreateTemplateColorFader(BattleUnit& self, int a0);
void BattleUnitCreateFootStepEffectHuman(BattleUnit& self, const char* a0);
void BattleUnitCreateUserDataParticleMan(BattleUnit& self);
void BattleUnitPlayAnimForceDirectEndPose(BattleUnit& self, AnimClip::Type a0);
void BattleUnitChangeToBeast(BattleUnit& self);
void BattleUnitSetup(BattleUnit& self);
void BattleUnitSetName(BattleUnit& self, const char* a0);
void BattleUnitPlayAnimName(BattleUnit& self, const char* a0);
void BattleUnitPlayAnimClip(BattleUnit& self, AnimClip::Type a0);
void BattleUnitRetarget(BattleUnit& self);
void BattleUnitLoadAsync(BattleUnit& self, BattleUnitResName& a0);
void BattleUnitMakeDirty(BattleUnit& self, const BattlePhase* a0);
void BattleUnitPlayVoice(BattleUnit& self, const char* a0);
void BattleUnitStabilize(BattleUnit& self);
void BattleUnitSyncWaste(BattleUnit& self);
void BattleUnitUpdateDir(BattleUnit& self);
void BattleUnitUpdatePos(BattleUnit& self);
void BattleUnitBattleUnit(BattleUnit& self, SceneSystem* a0, int a1);
void BattleUnitBattleUnit(BattleUnit& self);
void BattleUtilSuspendMap();
int BattleUtilGetBossType();
void BattleUtilHideMapIcon();
void BattleUtilHideMapUnit();
void BattleUtilShowMapIcon();
void BattleUtilShowMapUnit();
bool BattleUtilIsBossBattle();
bool BattleUtilIsBossUsable();
nn::math::VEC3 BattleUtilGetZoomTarget(const nn::math::VEC3& a0);
void BattleUtilResetUnitIcon(bool a0);
void BattleUtilBattleFinalize();
bool BattleUtilIsChangeBattle();
void BattleUtilOpenBattleArea(const Unit* a0);
int BattleUtilGetBossUnitSide();
void BattleUtilComebackUnitIcon(float a0, float a1);
void BattleUtilUpdateBattleArea();
void BattleUtilDeleteBattleUnits();
void BattleUtilEncounterUnitIcon(float a0, float a1);
void BattleSeqChangeLoad();
void BattleUtilResetBattleStance();
int BattleUtilGetCurrentUnitSide();
void BattleUtilResetDistanceStance(float a0);
bool BattleUtilIsLoadingBattleUnits();
void BattleUtilBindMap();
void BattleUtilResumeMap();
void BattleUtilUnbindMap();
void BattleWorldDraw(BattleWorld& self);
void BattleWorldTick(BattleWorld& self);
void BattleUtilBattleInitialize();
void BattleWorldInitialize();
void BattleWorldOnPostDraw(BattleWorld& self);
BattleUnit* BattleWorldCreateBattleUnit(BattleWorld& self, int a0);
void BattleWorldDeleteBattleUnit(BattleWorld& self, int a0);
void BattleWorldDeleteDisplayObjects(BattleWorld& self);
BattleWorld* BattleWorldGet();
void BattleWorldFinalize();
void BattleWorldOnPreDraw(BattleWorld& self);
void BattleWorldBattleWorld(BattleWorld& self);
void BattleWorldBattleWorld(BattleWorld& self);
void BattleWorldOnPostTick(BattleWorld& self);
void BattleWorldOnPreTick(BattleWorld& self);
bool BattleControllerIsBlurring();
bool BattleControllerDetectRunning();
void BattleControllerCreate(ProcInst* a0, map::BattleCalculator* a1);
void BattleControllerWakeup();
ProcInst* BattleControllerGetProc();
bool BattleControllerIsRunning();
void BattleSeqChangeFree();
void BattleSeqInitialize();
void BattleSeqPersistent();
void BattleSeqBeginBranch();
void BattleSeqHideMapIcon();
void BattleSeqHideMapUnit();
void BattleSeqResetOnSkip();
void BattleSeqShowMapIcon();
void BattleSeqShowMapUnit();
void BattleSeqWaitLoading();
void BattleSeqChangeResume();
void BattleSeqReturnBranch();
void BattleSeqChangeSuspend();
void BattleSeqEndFadeMapSound();
void BattleSeqUpdateBattleArea();
void BattleSeqBeginFadeMapSound();
void BattleSeqBuildActionStates();
void BattleSeqCreateBattleUnits();
void BattleSeqEndFadeBattleSound();
void BattleSeqBeginFadeBattleSound();
void BattleSeqResetInitialLocation();
void BattleSeqSleep();
void BattleSeqFinalize();
void BattleSeqMainLoop();
void BattleSeqEndBranch();
void BattleUtilResetBattleArea();
const BattleUnitResName* BattleUnitGetResName(const BattleUnit& self);
nn::math::VEC3 BattleUnitGetFocusPos(const BattleUnit& self);
float BattleUnitGetTimeRate(const BattleUnit& self);
AnimClip::Type BattleUnitGetReadyAnim(const BattleUnit& self);
int BattleUnitGetDeathLevel(const BattleUnit& self);
const BattleUnitParams* BattleUnitGetUnitParams(const BattleUnit& self);
bool BattleUnitIsAnimFinished(const BattleUnit& self);
BattleUnit* BattleUnitOpponentPartner(const BattleUnit& self);
nn::math::VEC3 BattleUnitCalcDualChildPos(const BattleUnit& self, VEC2XZ& a0, VEC2XZ& a1, const VEC2XZ& a2, const VEC2XZ& a3, float a4);
int BattleUnitGetMaterialEmotion(const BattleUnit& self);
std::uint8_t BattleUnitGetMaterialOpacity(const BattleUnit& self);
AnimClip::Type BattleUnitGetBattleInitialAnim(const BattleUnit& self);
nn::math::VEC3 BattleUnitGetActiveHandSlashVec(const BattleUnit& self, nn::math::VEC3& a0, nn::math::VEC3& a1, bool a2);
nn::math::VEC2 BattleUnitGetMaterialEyePosition(const BattleUnit& self);
bool BattleUnitIsLeftSideOnScreenSpace(const BattleUnit& self);
int BattleUnitFindNamedActorAndBoneIndex(const BattleUnit& self, const char* a0, int& a1);
const char* BattleUnitGetName(const BattleUnit& self);
bool BattleUnitIsNamed(const BattleUnit& self, const char* a0);
BattleUnit* BattleUnitPartner(const BattleUnit& self);
AABB BattleUnitCalcAABB(const BattleUnit& self);
BattleUnit* BattleUnitOpponent(const BattleUnit& self);
void BattleUnitAreaClampXZ(const BattleUnit& self, VEC2XZ& a0, float a1);
void BattleUnitAreaClampVec3(const BattleUnit& self, nn::math::VEC3& a0, float a1);
bool BattleUnitIsStealth(const BattleUnit& self);
}
