#pragma once
#include "fates/graphics/basic_types.hpp"
class CameraInput; class CameraTrack; class CameraParam; class CameraState; class ICamera; class AutoCamera; class EventCamera; class FieldCamera; class FixedCamera; class BattleCamera; class ProcInst;
namespace game::graphics { class CameraBase; }
namespace CameraConst { enum class Mode:int; }
namespace fates::decomp_detail {
float CameraCurveValue(int type,float a,float b,float c,float d);
void CameraInputTick(CameraInput& input,int type,float dt,float horizontal,float vertical);
void AutoCameraTick(AutoCamera& camera); void AutoCameraEnter(AutoCamera& camera); void AutoCameraDispose(AutoCamera& camera);
void EventCameraBuildTrack(EventCamera& camera,const CameraTrack* track); void EventCameraTick(EventCamera& camera); void EventCameraEnter(EventCamera& camera); void EventCameraLeave(EventCamera& camera);
void SetEventFarClipExpandPoint(const nn::math::VEC3& point,float radius); void ResetEventFarClipExpandPoint();
void FieldCameraUpdateProjection(FieldCamera& camera); void FieldCameraUpdateView(FieldCamera& camera); void FieldCameraTick(FieldCamera& camera,float dt); void RegisterFieldCamera(FieldCamera* camera); void UnregisterFieldCamera(FieldCamera* camera); bool FieldCameraControlBound(const FieldCamera& camera);
void FixedCameraUpdateParam(FixedCamera& camera,const CameraParam& param); void FixedCameraUpdateDirection(FixedCamera& camera);
bool BattleCameraCanChangeMode(const BattleCamera& camera); CameraState* CreateBattleCameraState(CameraConst::Mode mode); void BattleCameraShake(BattleCamera& camera); void BattleCameraUpdateUnits(BattleCamera& camera); void BattleCameraApply(BattleCamera& camera); float BattleCameraFocusFactor(const BattleCamera& camera); float BattleCameraFocusLength(const BattleCamera& camera); bool BattleCameraInputAllowed(const BattleCamera& camera);
int CameraBaseBlendFrames(int input); float CameraBaseMoveRatio(const game::graphics::CameraBase& camera,int frame); nn::math::VEC3 CameraBaseLimitTarget(const game::graphics::CameraBase& camera,const nn::math::VEC3& target,float margin); float CameraBaseMapHeight(float x,float z); void CameraBaseCalculateDraw(game::graphics::CameraBase& camera); void CameraBaseInstantConfig(game::graphics::CameraBase& camera); void CameraBaseInstantTarget(game::graphics::CameraBase& camera); void CameraBaseShake(game::graphics::CameraBase& camera,ProcInst* proc,float power,int duration,int curve,float extra,bool castle); void CameraBaseStopShake(game::graphics::CameraBase& camera,int id,float fade); float CameraBaseConfigAngle(int index); float CameraBaseConfigDistance(int index); void CameraBaseWriteConfigAngle(const game::graphics::CameraBase& camera); void CameraBaseWriteConfigDistance(const game::graphics::CameraBase& camera); void CameraBaseImportCastle(game::graphics::CameraBase& camera,ICamera* source); bool CameraBaseScrollProlixity(const game::graphics::CameraBase& camera); bool CameraBaseAngleProlixity(const game::graphics::CameraBase& camera); bool CameraBaseDistanceProlixity(const game::graphics::CameraBase& camera);
nn::math::VEC3 CameraHitPos(const nn::math::VEC3& p); nn::math::VEC3 CameraHitArea(const nn::math::VEC3& eye,const nn::math::VEC3& at); bool CameraIsLongRange(); bool CameraIsCloseRange(); bool CameraCutChanged(const nn::math::VEC3& a,const nn::math::VEC3& b); void CalcTPSCamera(CameraParam& p,int side); void CalcBossCamera(CameraParam& p,const char* name); void CalcHeadCamera(CameraParam& p,const nn::math::VEC3& pos,const nn::math::VEC3& rot); void CalcRotateCamera(CameraParam& p,const char* name,const nn::math::VEC3& dir,bool flip); void CalcTargetCamera(CameraParam& p,const char* name,const nn::math::VEC3& dir,int unit,bool reverse); nn::math::VEC3 UnitFlatDir(); nn::math::VEC3 UnitHeadPos(int unit); nn::math::VEC3 UnitRootDir(bool enemy); nn::math::VEC3 UnitHeadRotate(int unit); const char* BossCameraName();
}
