#include "fates/battle/battle_runtime.hpp"
#include "fates/detail/battle_runtime.hpp"

void BattleSeq::ChangeLoad(){fates::decomp_detail::BattleSeqChangeLoad();}
void BattleSeq::ChangeFree(){fates::decomp_detail::BattleSeqChangeFree();}
void BattleSeq::Initialize(){fates::decomp_detail::BattleSeqInitialize();}
void BattleSeq::Persistent(){fates::decomp_detail::BattleSeqPersistent();}
void BattleSeq::BeginBranch(){fates::decomp_detail::BattleSeqBeginBranch();}
void BattleSeq::HideMapIcon(){fates::decomp_detail::BattleSeqHideMapIcon();}
void BattleSeq::HideMapUnit(){fates::decomp_detail::BattleSeqHideMapUnit();}
void BattleSeq::ResetOnSkip(){fates::decomp_detail::BattleSeqResetOnSkip();}
void BattleSeq::ShowMapIcon(){fates::decomp_detail::BattleSeqShowMapIcon();}
void BattleSeq::ShowMapUnit(){fates::decomp_detail::BattleSeqShowMapUnit();}
void BattleSeq::WaitLoading(){fates::decomp_detail::BattleSeqWaitLoading();}
void BattleSeq::ChangeResume(){fates::decomp_detail::BattleSeqChangeResume();}
void BattleSeq::ReturnBranch(){fates::decomp_detail::BattleSeqReturnBranch();}
void BattleSeq::ChangeSuspend(){fates::decomp_detail::BattleSeqChangeSuspend();}
void BattleSeq::EndFadeMapSound(){fates::decomp_detail::BattleSeqEndFadeMapSound();}
void BattleSeq::UpdateBattleArea(){fates::decomp_detail::BattleSeqUpdateBattleArea();}
void BattleSeq::BeginFadeMapSound(){fates::decomp_detail::BattleSeqBeginFadeMapSound();}
void BattleSeq::BuildActionStates(){fates::decomp_detail::BattleSeqBuildActionStates();}
void BattleSeq::CreateBattleUnits(){fates::decomp_detail::BattleSeqCreateBattleUnits();}
void BattleSeq::EndFadeBattleSound(){fates::decomp_detail::BattleSeqEndFadeBattleSound();}
void BattleSeq::BeginFadeBattleSound(){fates::decomp_detail::BattleSeqBeginFadeBattleSound();}
void BattleSeq::ResetInitialLocation(){fates::decomp_detail::BattleSeqResetInitialLocation();}
void BattleSeq::Sleep(){fates::decomp_detail::BattleSeqSleep();}
void BattleSeq::Finalize(){fates::decomp_detail::BattleSeqFinalize();}
void BattleSeq::MainLoop(){fates::decomp_detail::BattleSeqMainLoop();}
void BattleSeq::EndBranch(){fates::decomp_detail::BattleSeqEndBranch();}
