#include "fates/event/native_commands.hpp"
#include "fates/event/typed_event_commands.hpp"

namespace fates::event::native {
namespace {
constexpr CommandSpec kCommandSpecs[] = {
    {"ev::Warning", 0X003B06C4u, "anonymous_namespace::Warning(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::ArgsGetInt", 0X00534C54u, "anonymous_namespace::ArgsGetInt(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::ArgsGetString", 0X00534C2Cu, "anonymous_namespace::ArgsGetString(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::TimeGetSpeed", 0X003A8200u, "anonymous_namespace::TimeGetSpeed(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::TimeGetConfigSpeed", 0X003AC37Cu, "anonymous_namespace::TimeGetConfigSpeed(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::TimeMSecToFrame", 0X003AA92Cu, "anonymous_namespace::TimeMSecToFrame(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::TimeFrameToMSec", 0X003AA90Cu, "anonymous_namespace::TimeFrameToMSec(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::FlagEntryGlobal", 0X003A9ED4u, "anonymous_namespace::FlagEntryGlobal(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::FlagEntry", 0X003B0D18u, "anonymous_namespace::FlagEntry(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::FlagGet", 0X005084ECu, "anonymous_namespace::FlagGet(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::FlagSet", 0X003B0624u, "anonymous_namespace::FlagSet(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::FlagClr", 0X003B05E8u, "anonymous_namespace::FlagClr(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::VariableEntryGlobal", 0X003AD680u, "anonymous_namespace::VariableEntryGlobal(cmvm::CmContext*,const char*,int)", CommandFamily::Core},
    {"ev::VariableEntry", 0X003A911Cu, "anonymous_namespace::VariableEntry(cmvm::CmContext*,const char*,int)", CommandFamily::Core},
    {"ev::VariableGet", 0X0050BCB0u, "anonymous_namespace::VariableGet(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::VariableSet", 0X001E7FE8u, "anonymous_namespace::VariableSet(cmvm::CmContext*,const char*,int)", CommandFamily::Core},
    {"ev::VariableAdd", 0X001E7F50u, "anonymous_namespace::VariableAdd(cmvm::CmContext*,const char*,int)", CommandFamily::Core},
    {"ev::VariableInc", 0X003A7E78u, "anonymous_namespace::VariableInc(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::VariableDec", 0X003A7E58u, "anonymous_namespace::VariableDec(cmvm::CmContext*,const char*)", CommandFamily::Core},
    {"ev::RandomGetGame", 0X003A8BC4u, "anonymous_namespace::RandomGetGame(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::RandomGetSystem", 0X003AA868u, "anonymous_namespace::RandomGetSystem(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::SkipTrigger", 0X003A7AF8u, "anonymous_namespace::SkipTrigger(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::SkipEscape", 0X003A7224u, "anonymous_namespace::SkipEscape(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::SkipEnable", 0X003A71FCu, "anonymous_namespace::SkipEnable(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::SkipDisable", 0X003A7AD0u, "anonymous_namespace::SkipDisable(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::SkipIsActive", 0X003A81F0u, "anonymous_namespace::SkipIsActive(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::SkipIsDisable", 0X003A8BD0u, "anonymous_namespace::SkipIsDisable(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::FadeIn", 0X003AF594u, "anonymous_namespace::FadeIn(cmvm::CmContext*,int,int,int)", CommandFamily::ChapterUi},
    {"ev::FadeOut", 0X003B04ECu, "anonymous_namespace::FadeOut(cmvm::CmContext*,int,int,int)", CommandFamily::ChapterUi},
    {"ev::FadeIsWait", 0X003A7110u, "anonymous_namespace::FadeIsWait(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::Talk", 0X003AF36Cu, "anonymous_namespace::Talk(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TalkNoShadowFrame", 0X003ABC48u, "anonymous_namespace::TalkNoShadowFrame(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog1", 0X003AF6E8u, "anonymous_namespace::Dialog1(cmvm::CmContext*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog2", 0X003AF7F0u, "anonymous_namespace::Dialog2(cmvm::CmContext*,const char*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog3", 0X003AF92Cu, "anonymous_namespace::Dialog3(cmvm::CmContext*,const char*,const char*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog4", 0X003AFA9Cu, "anonymous_namespace::Dialog4(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog5", 0X003AFC40u, "anonymous_namespace::Dialog5(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog6", 0X003AFE14u, "anonymous_namespace::Dialog6(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog7", 0X003B0018u, "anonymous_namespace::Dialog7(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::Dialog8", 0X003B0248u, "anonymous_namespace::Dialog8(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*)", CommandFamily::ChapterUi},
    {"ev::DialogYesNo", 0X003A785Cu, "anonymous_namespace::DialogYesNo(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::DialogGetResult", 0X003A9D84u, "anonymous_namespace::DialogGetResult(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::RouteBranchDialog", 0X003ABA98u, "anonymous_namespace::RouteBranchDialog(cmvm::CmContext*,const char*,const char*,const char*,const char*,int)", CommandFamily::ChapterUi},
    {"ev::RouteBranchBegin", 0X003AB06Cu, "anonymous_namespace::RouteBranchBegin(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::RouteBranchEnd", 0X003A9590u, "anonymous_namespace::RouteBranchEnd(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterGetName", 0X003A92E8u, "anonymous_namespace::ChapterGetName(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterGetEncountName", 0X003ADBA8u, "anonymous_namespace::ChapterGetEncountName(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterGetVersusName", 0X003AD770u, "anonymous_namespace::ChapterGetVersusName(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterIsCID", 0X003A7F44u, "anonymous_namespace::ChapterIsCID(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWinRuleBreakdown", 0X003AED04u, "anonymous_namespace::ChapterSetWinRuleBreakdown(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWinRuleDestroyBoss", 0X003AEF44u, "anonymous_namespace::ChapterSetWinRuleDestroyBoss(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWinRuleEscape", 0X003AE718u, "anonymous_namespace::ChapterSetWinRuleEscape(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWinRuleEscapeHero", 0X003AEEECu, "anonymous_namespace::ChapterSetWinRuleEscapeHero(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWinRuleEnemyNumberLessThanOrEqualTo", 0X003AF354u, "anonymous_namespace::ChapterSetWinRuleEnemyNumberLessThanOrEqualTo(cmvm::CmContext*,int)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWinRuleLimitTurn", 0X003AED30u, "anonymous_namespace::ChapterSetWinRuleLimitTurn(cmvm::CmContext*,int)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWinRuleMessageIndex", 0X003AEFECu, "anonymous_namespace::ChapterSetWinRuleMessageIndex(cmvm::CmContext*,int)", CommandFamily::ChapterUi},
    {"ev::ChapterShowWinRuleTelopImpl", 0X00361890u, "anonymous_namespace::ChapterShowWinRuleTelopImpl(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterGetWinLoseResult", 0X003AE6E8u, "anonymous_namespace::ChapterGetWinLoseResult(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterSetWin", 0X003A8A50u, "anonymous_namespace::ChapterSetWin(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterSetLose", 0X003A9310u, "anonymous_namespace::ChapterSetLose(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterSetTemporaryCasual", 0X003AEBE8u, "anonymous_namespace::ChapterSetTemporaryCasual(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetContinueAfterGameOver", 0X003AF198u, "anonymous_namespace::ChapterSetContinueAfterGameOver(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetSkipChapterSaveCastle", 0X003AF250u, "anonymous_namespace::ChapterSetSkipChapterSaveCastle(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetSkipSortie", 0X003AD7C8u, "anonymous_namespace::ChapterSetSkipSortie(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidSortieSaveBack", 0X003AF1F0u, "anonymous_namespace::ChapterSetInvalidSortieSaveBack(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetProhibitWarp", 0X003AE100u, "anonymous_namespace::ChapterSetProhibitWarp(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetHideSystemMenu", 0X003AE830u, "anonymous_namespace::ChapterSetHideSystemMenu(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetHideProperty", 0X003AE0B8u, "anonymous_namespace::ChapterSetHideProperty(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetHideTrade", 0X003AC7F4u, "anonymous_namespace::ChapterSetHideTrade(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetHideDouble", 0X003AD79Cu, "anonymous_namespace::ChapterSetHideDouble(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetHideAI", 0X003AAEE4u, "anonymous_namespace::ChapterSetHideAI(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetHideHpGauge", 0X003ADBE8u, "anonymous_namespace::ChapterSetHideHpGauge(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetExpMode", 0X003AB744u, "anonymous_namespace::ChapterSetExpMode(cmvm::CmContext*,int)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidPhoenix", 0X003AE85Cu, "anonymous_namespace::ChapterSetInvalidPhoenix(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidGainDragonVein", 0X003AF1C4u, "anonymous_namespace::ChapterSetInvalidGainDragonVein(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidGainReliance", 0X003AEFC0u, "anonymous_namespace::ChapterSetInvalidGainReliance(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidTransporter", 0X003AEF18u, "anonymous_namespace::ChapterSetInvalidTransporter(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidRecordKill", 0X003AEEC0u, "anonymous_namespace::ChapterSetInvalidRecordKill(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidRecordDead", 0X003AEE94u, "anonymous_namespace::ChapterSetInvalidRecordDead(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetInvalidFixedGain", 0X003AECD8u, "anonymous_namespace::ChapterSetInvalidFixedGain(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetValiedSurrender", 0X003AEC14u, "anonymous_namespace::ChapterSetValiedSurrender(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterAppear", 0X003A8A0Cu, "anonymous_namespace::ChapterAppear(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::ChapterIsCleared", 0X003AAE98u, "anonymous_namespace::ChapterIsCleared(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::ChapterIsCastleOffense", 0X003AE0A0u, "anonymous_namespace::ChapterIsCastleOffense(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterIsCastleSelfTest", 0X003AE700u, "anonymous_namespace::ChapterIsCastleSelfTest(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterGetTrickDragon", 0X003ADBD4u, "anonymous_namespace::ChapterGetTrickDragon(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterSetTrickDragon", 0X003ADC14u, "anonymous_namespace::ChapterSetTrickDragon(cmvm::CmContext*,int)", CommandFamily::ChapterUi},
    {"ev::ChapterSetNotReturnMap", 0X003AE0E4u, "anonymous_namespace::ChapterSetNotReturnMap(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::ChapterSetEscapeEffectWarp", 0X003AECACu, "anonymous_namespace::ChapterSetEscapeEffectWarp(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::ChapterSetResistInterferenceRod", 0X003AF224u, "anonymous_namespace::ChapterSetResistInterferenceRod(cmvm::CmContext*,bool)", CommandFamily::ChapterUi},
    {"ev::MessLoad", 0X003D1EA4u, "anonymous_namespace::MessLoad(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::MessFree", 0X003D1E10u, "anonymous_namespace::MessFree(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::MessSetArgumentByMID", 0X003D1604u, "anonymous_namespace::MessSetArgumentByMID(cmvm::CmContext*,int,const char*)", CommandFamily::ChapterUi},
    {"ev::MessSetArgumentByValue", 0X003D1648u, "anonymous_namespace::MessSetArgumentByValue(cmvm::CmContext*,int,int)", CommandFamily::ChapterUi},
    {"ev::PersonLoad", 0X0044A800u, "anonymous_namespace::PersonLoad(cmvm::CmContext*,const char*)", CommandFamily::UnitForce},
    {"ev::PersonFree", 0X0044A768u, "anonymous_namespace::PersonFree(cmvm::CmContext*,const char*)", CommandFamily::UnitForce},
    {"ev::TerrainLoad", 0X003426D4u, "anonymous_namespace::TerrainLoad(cmvm::CmContext*,const char*)", CommandFamily::AiMap},
    {"ev::TerrainLoadScript", 0X003ABCB8u, "anonymous_namespace::TerrainLoadScript(cmvm::CmContext*,const char*,const char*)", CommandFamily::AiMap},
    {"ev::TerrainLoadCastle", 0X003ABC8Cu, "anonymous_namespace::TerrainLoadCastle(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TerrainFree", 0X003A7B80u, "anonymous_namespace::TerrainFree(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TerrainGetW", 0X003A7BD0u, "anonymous_namespace::TerrainGetW(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TerrainGetH", 0X003A7BACu, "anonymous_namespace::TerrainGetH(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TerrainIsOutOfPlayArea", 0X003AE294u, "anonymous_namespace::TerrainIsOutOfPlayArea(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::TerrainDrawBegin", 0X003AB110u, "anonymous_namespace::TerrainDrawBegin(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TerrainDrawEnd", 0X003A95B8u, "anonymous_namespace::TerrainDrawEnd(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::DisposLoad", 0X0039ED84u, "anonymous_namespace::DisposLoad(cmvm::CmContext*,const char*)", CommandFamily::UnitForce},
    {"ev::DisposFree", 0X0039ED28u, "anonymous_namespace::DisposFree(cmvm::CmContext*)", CommandFamily::UnitForce},
    {"ev::Dispos", 0X0039DB4Cu, "anonymous_namespace::Dispos(cmvm::CmContext*,const char*,int)", CommandFamily::UnitForce},
    {"ev::DisposIsWait", 0X0039DFACu, "anonymous_namespace::DisposIsWait(cmvm::CmContext*)", CommandFamily::UnitForce},
    {"ev::ForceGetActive", 0X003A9490u, "anonymous_namespace::ForceGetActive(cmvm::CmContext*)", CommandFamily::UnitForce},
    {"ev::ForceUnitGetFirst", 0X003AB868u, "anonymous_namespace::ForceUnitGetFirst(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::ForceUnitGetNext", 0X003AAF70u, "anonymous_namespace::ForceUnitGetNext(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::ForceUnitGetCount", 0X003AB838u, "anonymous_namespace::ForceUnitGetCount(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::ForceUnitGetCountArea", 0X003ADD38u, "anonymous_namespace::ForceUnitGetCountArea(cmvm::CmContext*,int,int,int,int,int,bool)", CommandFamily::UnitForce},
    {"ev::ForceUnitTransfer", 0X003AB8A8u, "anonymous_namespace::ForceUnitTransfer(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::ForceUnitTransferExchange", 0X003AEC40u, "anonymous_namespace::ForceUnitTransferExchange(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::ForceUnitDelete", 0X003A9F10u, "anonymous_namespace::ForceUnitDelete(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::ForceUnitExpulsion", 0X003AB8A0u, "anonymous_namespace::ForceUnitExpulsion(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetByPID", 0X003A8390u, "anonymous_namespace::UnitGetByPID(cmvm::CmContext*,const char*)", CommandFamily::UnitForce},
    {"ev::UnitGetByPIDForce", 0X003ABE24u, "anonymous_namespace::UnitGetByPIDForce(cmvm::CmContext*,const char*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetByPosition", 0X003ABE80u, "anonymous_namespace::UnitGetByPosition(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitTransferByIndex", 0X003AD280u, "anonymous_namespace::UnitTransferByIndex(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitDeleteByIndex", 0X003ABDD0u, "anonymous_namespace::UnitDeleteByIndex(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitLostByIndex", 0X003AAD10u, "anonymous_namespace::UnitLostByIndex(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitExpulsionByIndex", 0X003AD278u, "anonymous_namespace::UnitExpulsionByIndex(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsAlive", 0X003A7C80u, "anonymous_namespace::UnitIsAlive(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsDoubleParent", 0X003AC5B0u, "anonymous_namespace::UnitIsDoubleParent(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsDoubleChild", 0X003ABF94u, "anonymous_namespace::UnitIsDoubleChild(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitSetPID", 0X003A768Cu, "anonymous_namespace::UnitSetPID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitIsPID", 0X003B0FE4u, "anonymous_namespace::UnitIsPID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitIsPIDWithGuest", 0X003AC5FCu, "anonymous_namespace::UnitIsPIDWithGuest(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitIsResidentFirstPID", 0X003AE4D0u, "anonymous_namespace::UnitIsResidentFirstPID(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsFatherPID", 0X003AAB58u, "anonymous_namespace::UnitIsFatherPID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitIsMotherPID", 0X003AABECu, "anonymous_namespace::UnitIsMotherPID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitSetJID", 0X003A75A0u, "anonymous_namespace::UnitSetJID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitIsJID", 0X003B0F78u, "anonymous_namespace::UnitIsJID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitIsHighJob", 0X003A8DA0u, "anonymous_namespace::UnitIsHighJob(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsJCID", 0X003A7494u, "anonymous_namespace::UnitIsJCID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitSetBID", 0X003A7550u, "anonymous_namespace::UnitSetBID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitIsBID", 0X003B0F18u, "anonymous_namespace::UnitIsBID(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitGetForce", 0X003A83C0u, "anonymous_namespace::UnitGetForce(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetX", 0X003B0AD0u, "anonymous_namespace::UnitGetX(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetY", 0X003B0B20u, "anonymous_namespace::UnitGetY(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitSetPosition", 0X003AAD88u, "anonymous_namespace::UnitSetPosition(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitSetPositionFreeSpace", 0X003AEA74u, "anonymous_namespace::UnitSetPositionFreeSpace(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitMovePosition", 0X003AB1A4u, "anonymous_namespace::UnitMovePosition(cmvm::CmContext*,int,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitMoveSlide", 0X003A8E84u, "anonymous_namespace::UnitMoveSlide(cmvm::CmContext*,int,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitSetAlpha", 0X003A86F4u, "anonymous_namespace::UnitSetAlpha(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitMoveAlphaDeadOut", 0X003ADA88u, "anonymous_namespace::UnitMoveAlphaDeadOut(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitMoveAlphaWarpIn", 0X003AD0C0u, "anonymous_namespace::UnitMoveAlphaWarpIn(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitMoveAlphaWarpOut", 0X003ADAF8u, "anonymous_namespace::UnitMoveAlphaWarpOut(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsMoveWait", 0X003A9858u, "anonymous_namespace::UnitIsMoveWait(cmvm::CmContext*)", CommandFamily::UnitForce},
    {"ev::UnitSetDontAttack", 0X003AC208u, "anonymous_namespace::UnitSetDontAttack(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitSetDontAttackForce", 0X003AE684u, "anonymous_namespace::UnitSetDontAttackForce(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitGetLevel", 0X003A8408u, "anonymous_namespace::UnitGetLevel(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetInternalLevel", 0X003AD910u, "anonymous_namespace::UnitGetInternalLevel(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetHP", 0X003B0ED4u, "anonymous_namespace::UnitGetHP(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetMHP", 0X003A73D8u, "anonymous_namespace::UnitGetMHP(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitSetHP", 0X003B105Cu, "anonymous_namespace::UnitSetHP(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitGetCapability", 0X003ABEC0u, "anonymous_namespace::UnitGetCapability(cmvm::CmContext*,int,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitSetCapability", 0X003AC1B8u, "anonymous_namespace::UnitSetCapability(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitGetMovePower", 0X0052D580u, "anonymous_namespace::UnitGetMovePower(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitSetMovePower", 0X003AB694u, "anonymous_namespace::UnitSetMovePower(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitGetWeaponLevel", 0X003AC430u, "anonymous_namespace::UnitGetWeaponLevel(cmvm::CmContext*,int,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitGetMarrigeUnit", 0X003AC3C0u, "anonymous_namespace::UnitGetMarrigeUnit(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitGetRecordKill", 0X003ABF50u, "anonymous_namespace::UnitGetRecordKill(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemIsExist", 0X003AAC80u, "anonymous_namespace::UnitItemIsExist(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitItemAddDirect", 0X003ABFE0u, "anonymous_namespace::UnitItemAddDirect(cmvm::CmContext*,int,const char*,bool)", CommandFamily::UnitForce},
    {"ev::UnitItemPutOff", 0X003A994Cu, "anonymous_namespace::UnitItemPutOff(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitItemPutOffAll", 0X003AC124u, "anonymous_namespace::UnitItemPutOffAll(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemToTransporter", 0X003ADF84u, "anonymous_namespace::UnitItemToTransporter(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemDisposalFor006", 0X003AE518u, "anonymous_namespace::UnitItemDisposalFor006(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemEquip", 0X003A8E34u, "anonymous_namespace::UnitItemEquip(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemEquip2", 0X003A98B4u, "anonymous_namespace::UnitItemEquip2(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitItemClearEquip", 0X003AC674u, "anonymous_namespace::UnitItemClearEquip(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemClearDrop", 0X003AC058u, "anonymous_namespace::UnitItemClearDrop(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemSetEndurance", 0X003AD9D4u, "anonymous_namespace::UnitItemSetEndurance(cmvm::CmContext*,int,const char*,int)", CommandFamily::UnitForce},
    {"ev::UnitItemSetInvalidRefine", 0X003AEA0Cu, "anonymous_namespace::UnitItemSetInvalidRefine(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitShowDanger", 0X003A9AA4u, "anonymous_namespace::UnitShowDanger(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitShowWholeDanger", 0X003AD1ACu, "anonymous_namespace::UnitShowWholeDanger(cmvm::CmContext*,bool)", CommandFamily::UnitForce},
    {"ev::UnitSetPrivateSkill", 0X003AD134u, "anonymous_namespace::UnitSetPrivateSkill(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitClrPrivateSkill", 0X003AD03Cu, "anonymous_namespace::UnitClrPrivateSkill(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitTstPrivateSkill", 0X003AD5E8u, "anonymous_namespace::UnitTstPrivateSkill(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitCanDragonVein", 0X003ABD8Cu, "anonymous_namespace::UnitCanDragonVein(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsEquipSkill", 0X003AB148u, "anonymous_namespace::UnitIsEquipSkill(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitAddEquipSkill", 0X003ABCDCu, "anonymous_namespace::UnitAddEquipSkill(cmvm::CmContext*,int,const char*)", CommandFamily::UnitForce},
    {"ev::UnitDoubleOn", 0X003A8290u, "anonymous_namespace::UnitDoubleOn(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitDoubleOff", 0X003A8CE4u, "anonymous_namespace::UnitDoubleOff(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitBackup", 0X003A734Cu, "anonymous_namespace::UnitBackup(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitRestore", 0X003A7D58u, "anonymous_namespace::UnitRestore(cmvm::CmContext*,int,bool,bool)", CommandFamily::UnitForce},
    {"ev::UnitBackupDiscard", 0X003ABD34u, "anonymous_namespace::UnitBackupDiscard(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitHpDamage", 0X003A844Cu, "anonymous_namespace::UnitHpDamage(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitHpHeal", 0X003A7428u, "anonymous_namespace::UnitHpHeal(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitIsHpEffectWait", 0X0035EAE0u, "anonymous_namespace::UnitIsHpEffectWait(cmvm::CmContext*)", CommandFamily::UnitForce},
    {"ev::UnitSetEnhance", 0X003A99E8u, "anonymous_namespace::UnitSetEnhance(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitClrEnhance", 0X003A97FCu, "anonymous_namespace::UnitClrEnhance(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitTstEnhance", 0X003A9BF0u, "anonymous_namespace::UnitTstEnhance(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitGetWeakness", 0X003AAB0Cu, "anonymous_namespace::UnitGetWeakness(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitAddWeakness", 0X003AA94Cu, "anonymous_namespace::UnitAddWeakness(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitMergeWeakness", 0X003AC164u, "anonymous_namespace::UnitMergeWeakness(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitCreateClone", 0X003AA9A0u, "anonymous_namespace::UnitCreateClone(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitIsClone", 0X003A7CC0u, "anonymous_namespace::UnitIsClone(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitSetNeverSortie", 0X003AC6DCu, "anonymous_namespace::UnitSetNeverSortie(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitRecreate", 0X003A84B8u, "anonymous_namespace::UnitRecreate(cmvm::CmContext*,int,const char*,int)", CommandFamily::UnitForce},
    {"ev::UnitSetPhantom", 0X003A9A44u, "anonymous_namespace::UnitSetPhantom(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitIsPhantom", 0X003A8DE8u, "anonymous_namespace::UnitIsPhantom(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitTstStatus", 0X003A90B8u, "anonymous_namespace::UnitTstStatus(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitSetStatus", 0X003A9060u, "anonymous_namespace::UnitSetStatus(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitClrStatus", 0X003A8C8Cu, "anonymous_namespace::UnitClrStatus(cmvm::CmContext*,int,int,int)", CommandFamily::UnitForce},
    {"ev::UnitIsAbleToAttack", 0X003AC4A4u, "anonymous_namespace::UnitIsAbleToAttack(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitIsSleep", 0X003A7D0Cu, "anonymous_namespace::UnitIsSleep(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitSetMotion", 0X003A900Cu, "anonymous_namespace::UnitSetMotion(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitGetRelianceLevel", 0X003AD958u, "anonymous_namespace::UnitGetRelianceLevel(cmvm::CmContext*,int,int)", CommandFamily::UnitForce},
    {"ev::UnitSetInvalidEternal", 0X003ADFFCu, "anonymous_namespace::UnitSetInvalidEternal(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitSetInvalidUseDoping", 0X003AE744u, "anonymous_namespace::UnitSetInvalidUseDoping(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitSetInvalidUseClassChange", 0X003AEF70u, "anonymous_namespace::UnitSetInvalidUseClassChange(cmvm::CmContext*,int,bool)", CommandFamily::UnitForce},
    {"ev::UnitShine", 0X003B10F8u, "anonymous_namespace::UnitShine(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitSetDummyIcon", 0X003AB62Cu, "anonymous_namespace::UnitSetDummyIcon(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::AiSetSequence", 0X003A8934u, "anonymous_namespace::AiSetSequence(cmvm::CmContext*,int,int,const char*,const char*)", CommandFamily::AiMap},
    {"ev::AiTstFlag", 0X003B0C44u, "anonymous_namespace::AiTstFlag(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::AiSetFlag", 0X003B0BFCu, "anonymous_namespace::AiSetFlag(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::AiClrFlag", 0X003B0B70u, "anonymous_namespace::AiClrFlag(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::AiSetBattleRate", 0X003A9C4Cu, "anonymous_namespace::AiSetBattleRate(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::AiSetHealRate", 0X003A88ACu, "anonymous_namespace::AiSetHealRate(cmvm::CmContext*,int,int,int)", CommandFamily::AiMap},
    {"ev::AiGetHealRateA", 0X003A917Cu, "anonymous_namespace::AiGetHealRateA(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::AiGetHealRateB", 0X003A91C0u, "anonymous_namespace::AiGetHealRateB(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::AiSetActive", 0X003A776Cu, "anonymous_namespace::AiSetActive(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::AiGetActive", 0X003A7728u, "anonymous_namespace::AiGetActive(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::AiGetBand", 0X003B0BB8u, "anonymous_namespace::AiGetBand(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::AiSetMoveLimit", 0X003A9204u, "anonymous_namespace::AiSetMoveLimit(cmvm::CmContext*,int,int,int,int,int,int)", CommandFamily::AiMap},
    {"ev::AiGetDisposX", 0X003A7E98u, "anonymous_namespace::AiGetDisposX(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::AiGetDisposY", 0X003A7EDCu, "anonymous_namespace::AiGetDisposY(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::AiSetDisposPosition", 0X003AC77Cu, "anonymous_namespace::AiSetDisposPosition(cmvm::CmContext*,int,int,int)", CommandFamily::AiMap},
    {"ev::AiGetPriority", 0X003A8868u, "anonymous_namespace::AiGetPriority(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::AiSetPriority", 0X003A88F4u, "anonymous_namespace::AiSetPriority(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::TransporterItemIsExist", 0X003AE2F0u, "anonymous_namespace::TransporterItemIsExist(cmvm::CmContext*,const char*)", CommandFamily::UnitForce},
    {"ev::TransporterItemPutOff", 0X003ADF04u, "anonymous_namespace::TransporterItemPutOff(cmvm::CmContext*,const char*)", CommandFamily::UnitForce},
    {"ev::TransporterItemSetInvalidRefine", 0X001A6EF8u, "anonymous_namespace::TransporterItemSetInvalidRefine(cmvm::CmContext*,bool)", CommandFamily::UnitForce},
    {"ev::TerrainAttributeSetTID", 0X003AE1B0u, "anonymous_namespace::TerrainAttributeSetTID(cmvm::CmContext*,int,int,const char*)", CommandFamily::AiMap},
    {"ev::TerrainAttributeIsTID", 0X003ADE7Cu, "anonymous_namespace::TerrainAttributeIsTID(cmvm::CmContext*,int,int,const char*)", CommandFamily::AiMap},
    {"ev::TerrainAttributeIsTIDWithEdge", 0X003AF020u, "anonymous_namespace::TerrainAttributeIsTIDWithEdge(cmvm::CmContext*,int,int,const char*)", CommandFamily::AiMap},
    {"ev::TerrainAttributeIsFlag", 0X003AE12Cu, "anonymous_namespace::TerrainAttributeIsFlag(cmvm::CmContext*,int,int,int)", CommandFamily::AiMap},
    {"ev::TerrainAttributeRemoveObstacle", 0X003AF0A0u, "anonymous_namespace::TerrainAttributeRemoveObstacle(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TerrainAttributeUpdatePosition", 0X003AF16Cu, "anonymous_namespace::TerrainAttributeUpdatePosition(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::TerrainAttributeUpdateArea", 0X003AEDFCu, "anonymous_namespace::TerrainAttributeUpdateArea(cmvm::CmContext*,int,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickGetForce", 0X003A8BE0u, "anonymous_namespace::TrickGetForce(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TrickSetForce", 0X003A8C70u, "anonymous_namespace::TrickSetForce(cmvm::CmContext*,int)", CommandFamily::AiMap},
    {"ev::TrickSet", 0X003B093Cu, "anonymous_namespace::TrickSet(cmvm::CmContext*,int,int,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickStringSet", 0X003A95DCu, "anonymous_namespace::TrickStringSet(cmvm::CmContext*,const char*,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickTst", 0X003B0A44u, "anonymous_namespace::TrickTst(cmvm::CmContext*,int,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickTryTst", 0X003A7BF4u, "anonymous_namespace::TrickTryTst(cmvm::CmContext*,int,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickGetHp", 0X003A724Cu, "anonymous_namespace::TrickGetHp(cmvm::CmContext*,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickSetHp", 0X003A72C8u, "anonymous_namespace::TrickSetHp(cmvm::CmContext*,int,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickGetMaxHp", 0X003A8BF4u, "anonymous_namespace::TrickGetMaxHp(cmvm::CmContext*,int,int,int)", CommandFamily::AiMap},
    {"ev::TrickGetDragonAccessX", 0X003ADF5Cu, "anonymous_namespace::TrickGetDragonAccessX(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TrickGetDragonAccessY", 0X003ADF70u, "anonymous_namespace::TrickGetDragonAccessY(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::TrickSetDragonFocus", 0X003AD024u, "anonymous_namespace::TrickSetDragonFocus(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::GimmickMedicine", 0X003AC8D4u, "anonymous_namespace::GimmickMedicine(cmvm::CmContext*,int,int)", CommandFamily::AiMap},
    {"ev::GimmickMedicineString", 0X003ADE00u, "anonymous_namespace::GimmickMedicineString(cmvm::CmContext*,const char*)", CommandFamily::AiMap},
    {"ev::GimmickWindBlow", 0X003AA030u, "anonymous_namespace::GimmickWindBlow(cmvm::CmContext*,int,int,int,int,bool)", CommandFamily::AiMap},
    {"ev::MindGetForce", 0X003A80FCu, "anonymous_namespace::MindGetForce(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MindGetUnit", 0X003A7AC0u, "anonymous_namespace::MindGetUnit(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MindGetX", 0X003B07D0u, "anonymous_namespace::MindGetX(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MindGetY", 0X003B07E0u, "anonymous_namespace::MindGetY(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MindGetMind", 0X003A7AB0u, "anonymous_namespace::MindGetMind(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MindGetTargetUnit", 0X003ABA88u, "anonymous_namespace::MindGetTargetUnit(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MindGetTradeUnit", 0X003AAFCCu, "anonymous_namespace::MindGetTradeUnit(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::RouteGet", 0X003B0874u, "anonymous_namespace::RouteGet(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::RouteSet", 0X003B0884u, "anonymous_namespace::RouteSet(cmvm::CmContext*,int)", CommandFamily::ChapterUi},
    {"ev::RouteIsBought", 0X001AC9B0u, "anonymous_namespace::RouteIsBought(cmvm::CmContext*,int)", CommandFamily::ChapterUi},
    {"ev::ContentsGetPackage", 0X001ACBE4u, "anonymous_namespace::ContentsGetPackage(void)", CommandFamily::Core},
    {"ev::DifficultyGet", 0X003A8A70u, "anonymous_namespace::DifficultyGet(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::DifficultyIsCasual", 0X003AC324u, "anonymous_namespace::DifficultyIsCasual(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::DifficultyIsPhoenix", 0X003AC820u, "anonymous_namespace::DifficultyIsPhoenix(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::ScenarioRankGet", 0X003AA874u, "anonymous_namespace::ScenarioRankGet(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::TurnGet", 0X003B06B0u, "anonymous_namespace::TurnGet(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::ItemGain", 0X003B0768u, "anonymous_namespace::ItemGain(cmvm::CmContext*,int,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemGainNoSound", 0X003AA52Cu, "anonymous_namespace::ItemGainNoSound(cmvm::CmContext*,int,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemGainSilent", 0X003A94A4u, "anonymous_namespace::ItemGainSilent(cmvm::CmContext*,int,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemReplaceForYatonokami", 0X003AE888u, "anonymous_namespace::ItemReplaceForYatonokami(cmvm::CmContext*,const char*,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemGainMessageOnly", 0X003ACF6Cu, "anonymous_namespace::ItemGainMessageOnly(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemGainMessageOnlyNoSound", 0X003AED48u, "anonymous_namespace::ItemGainMessageOnlyNoSound(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemGetKind", 0X003A7A7Cu, "anonymous_namespace::ItemGetKind(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemGetOrigin", 0X003A8AE4u, "anonymous_namespace::ItemGetOrigin(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::ItemGetRandom", 0X003A8B14u, "anonymous_namespace::ItemGetRandom(cmvm::CmContext*,int,int,int)", CommandFamily::InventorySocial},
    {"ev::GoldGain", 0X003B0728u, "anonymous_namespace::GoldGain(cmvm::CmContext*,int,int)", CommandFamily::InventorySocial},
    {"ev::GoldGain2", 0X003B0D70u, "anonymous_namespace::GoldGain2(cmvm::CmContext*,int,int,const char*)", CommandFamily::InventorySocial},
    {"ev::GoldGainSilent", 0X0035EA64u, "anonymous_namespace::GoldGainSilent(cmvm::CmContext*,int,int)", CommandFamily::InventorySocial},
    {"ev::GoldGet", 0X003B0660u, "anonymous_namespace::GoldGet(cmvm::CmContext*)", CommandFamily::InventorySocial},
    {"ev::AccessoryGain", 0X003A874Cu, "anonymous_namespace::AccessoryGain(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::AccessoryGainSilent", 0X003AC744u, "anonymous_namespace::AccessoryGainSilent(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::EffectPlay3D", 0X003A7FA4u, "anonymous_namespace::EffectPlay3D(cmvm::CmContext*,const char*,int,int)", CommandFamily::PresentationField},
    {"ev::EffectPlayEternal3D", 0X003AC838u, "anonymous_namespace::EffectPlayEternal3D(cmvm::CmContext*,const char*,int,int)", CommandFamily::PresentationField},
    {"ev::EffectPlayUnit", 0X003A9348u, "anonymous_namespace::EffectPlayUnit(cmvm::CmContext*,const char*,int)", CommandFamily::PresentationField},
    {"ev::EffectRotate", 0X003A80B4u, "anonymous_namespace::EffectRotate(cmvm::CmContext*,int,int)", CommandFamily::PresentationField},
    {"ev::EffectFadeOut", 0X003A8A80u, "anonymous_namespace::EffectFadeOut(cmvm::CmContext*,int,int)", CommandFamily::PresentationField},
    {"ev::EffectDelete", 0X003A7F78u, "anonymous_namespace::EffectDelete(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::EffectIsPreload", 0X003A9DD8u, "anonymous_namespace::EffectIsPreload(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::EffectIsPlaying", 0X003A9DB8u, "anonymous_namespace::EffectIsPlaying(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::EffectHideTrick", 0X003A9DB0u, "anonymous_namespace::EffectHideTrick(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::EffectShowTrick", 0X003A9E04u, "anonymous_namespace::EffectShowTrick(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::TelopPlay", 0X003B0E4Cu, "anonymous_namespace::TelopPlay(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TelopPlayDirect", 0X003AA884u, "anonymous_namespace::TelopPlayDirect(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TelopIsWait", 0X003A7B08u, "anonymous_namespace::TelopIsWait(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::TutorialIsEnable", 0X003AB12Cu, "anonymous_namespace::TutorialIsEnable(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::TutorialShow", 0X003A8210u, "anonymous_namespace::TutorialShow(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TutorialGetFlag", 0X0050C980u, "anonymous_namespace::TutorialGetFlag(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TutorialSetFlag", 0X00202BB8u, "anonymous_namespace::TutorialSetFlag(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TutorialSetFlagAll", 0X003AC3ACu, "anonymous_namespace::TutorialSetFlagAll(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::TutorialDialog", 0X003A976Cu, "anonymous_namespace::TutorialDialog(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TutorialDialogMustShow", 0X003AE358u, "anonymous_namespace::TutorialDialogMustShow(cmvm::CmContext*,const char*)", CommandFamily::ChapterUi},
    {"ev::TutorialIsAbleToAttack", 0X003AE3D0u, "anonymous_namespace::TutorialIsAbleToAttack(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::TutorialIsAbleToTalkForPickEvent", 0X003AF284u, "anonymous_namespace::TutorialIsAbleToTalkForPickEvent(cmvm::CmContext*)", CommandFamily::ChapterUi},
    {"ev::MapSuspend", 0X003A7130u, "anonymous_namespace::MapSuspend(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MapResume", 0X003B0E24u, "anonymous_namespace::MapResume(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MapImageUpdate", 0X003A94E8u, "anonymous_namespace::MapImageUpdate(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::MoviePlayImpl", 0X003A8B80u, "anonymous_namespace::MoviePlayImpl(cmvm::CmContext*,const char*,bool)", CommandFamily::PresentationField},
    {"ev::MovieStop", 0X0041F108u, "anonymous_namespace::MovieStop(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::MovieIsExist", 0X003A81DCu, "anonymous_namespace::MovieIsExist(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::MovieIsPaused", 0X003A8B58u, "anonymous_namespace::MovieIsPaused(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::MovieIsSkipped", 0X0041F1A8u, "anonymous_namespace::MovieIsSkipped(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::MovieEnablePauseAtEnd", 0X0041F014u, "anonymous_namespace::MovieEnablePauseAtEnd(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::MovieDisablePauseAtEnd", 0X0041F0A0u, "anonymous_namespace::MovieDisablePauseAtEnd(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::Battle", 0X003AF3D8u, "anonymous_namespace::Battle(cmvm::CmContext*,int,int,int,int,const int*)", CommandFamily::AiMap},
    {"ev::JoinGuest", 0X003B0DB4u, "anonymous_namespace::JoinGuest(cmvm::CmContext*,const char*,bool)", CommandFamily::InventorySocial},
    {"ev::CardEntry", 0X003B0CC0u, "anonymous_namespace::CardEntry(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::CardIsExist", 0X003A7830u, "anonymous_namespace::CardIsExist(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::BGMPlay", 0X003AF674u, "anonymous_namespace::BGMPlay(cmvm::CmContext*,const char*,int)", CommandFamily::PresentationField},
    {"ev::BGMStop", 0X0041FB38u, "anonymous_namespace::BGMStop(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::RBGMPlay", 0X003B07F0u, "anonymous_namespace::RBGMPlay(cmvm::CmContext*,const char*,int)", CommandFamily::PresentationField},
    {"ev::RBGMStop", 0X003B084Cu, "anonymous_namespace::RBGMStop(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::RBGMEffect", 0X003A71A4u, "anonymous_namespace::RBGMEffect(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::BGMVolume", 0X003B0C90u, "anonymous_namespace::BGMVolume(cmvm::CmContext*,int,int)", CommandFamily::PresentationField},
    {"ev::EnableBGMCommandPG", 0X0041FAACu, "anonymous_namespace::EnableBGMCommandPG(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::DisableBGMCommandPG", 0X0041FB10u, "anonymous_namespace::DisableBGMCommandPG(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::BMapBGMChnageFlagOn", 0X003AC7C4u, "anonymous_namespace::BMapBGMChnageFlagOn(cmvm::CmContext*)", CommandFamily::Misc},
    {"ev::BMapBGMResume", 0X003A89D0u, "anonymous_namespace::BMapBGMResume(cmvm::CmContext*,int)", CommandFamily::Misc},
    {"ev::SEPlay", 0X003AF63Cu, "anonymous_namespace::SEPlay(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::SEPlay3D", 0X003B08A0u, "anonymous_namespace::SEPlay3D(cmvm::CmContext*,const char*,int,int)", CommandFamily::PresentationField},
    {"ev::LSEPlay", 0X003B0670u, "anonymous_namespace::LSEPlay(cmvm::CmContext*,const char*,int)", CommandFamily::Misc},
    {"ev::LSEStop", 0X00420344u, "anonymous_namespace::LSEStop(cmvm::CmContext*,const char*,int)", CommandFamily::Misc},
    {"ev::LSEVolume", 0X00420A48u, "anonymous_namespace::LSEVolume(cmvm::CmContext*,const char*,int,int)", CommandFamily::Misc},
    {"ev::Voice", 0X003AF3A0u, "anonymous_namespace::Voice(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::EnvSEOff", 0X003B06C8u, "anonymous_namespace::EnvSEOff(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::EnvSEOn", 0X003B04A4u, "anonymous_namespace::EnvSEOn(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::VoiceArchiveLoad", 0X0041FE2Cu, "anonymous_namespace::VoiceArchiveLoad(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::VoiceArchiveFree", 0X0041FD68u, "anonymous_namespace::VoiceArchiveFree(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::MiracleTelop", 0X003A81C0u, "anonymous_namespace::MiracleTelop(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::MiracleShoot", 0X003A8110u, "anonymous_namespace::MiracleShoot(cmvm::CmContext*,int,int,const char*)", CommandFamily::PresentationField},
    {"ev::MiracleShootXY", 0X003A9524u, "anonymous_namespace::MiracleShootXY(cmvm::CmContext*,int,int,int,int)", CommandFamily::PresentationField},
    {"ev::MiracleGetShootX", 0X003AAFDCu, "anonymous_namespace::MiracleGetShootX(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::MiracleGetShootY", 0X003AB024u, "anonymous_namespace::MiracleGetShootY(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::GMapMove", 0X003B06D0u, "anonymous_namespace::GMapMove(cmvm::CmContext*,const char*,const char*,unsigned int)", CommandFamily::AiMap},
    {"ev::FieldObjectPlayState", 0X003AD84Cu, "anonymous_namespace::FieldObjectPlayState(cmvm::CmContext*,const char*,int)", CommandFamily::PresentationField},
    {"ev::FieldObjectSetState", 0X003AC89Cu, "anonymous_namespace::FieldObjectSetState(cmvm::CmContext*,const char*,int)", CommandFamily::PresentationField},
    {"ev::FieldObjectSetVisible", 0X003ADD10u, "anonymous_namespace::FieldObjectSetVisible(cmvm::CmContext*,const char*,bool)", CommandFamily::PresentationField},
    {"ev::FieldObjectSetEscape", 0X003AD8E8u, "anonymous_namespace::FieldObjectSetEscape(cmvm::CmContext*,const char*,bool)", CommandFamily::PresentationField},
    {"ev::FieldObjectCreate", 0X003AB7B0u, "anonymous_namespace::FieldObjectCreate(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::FieldObjectDelete", 0X003AB7D4u, "anonymous_namespace::FieldObjectDelete(cmvm::CmContext*,const char*)", CommandFamily::PresentationField},
    {"ev::FieldObjectMove", 0X003A9E8Cu, "anonymous_namespace::FieldObjectMove(cmvm::CmContext*,const char*,int,int,const char*)", CommandFamily::PresentationField},
    {"ev::FieldObjectMoveEx", 0X003AB7F4u, "anonymous_namespace::FieldObjectMoveEx(cmvm::CmContext*,const char*,int,int,int,const char*)", CommandFamily::PresentationField},
    {"ev::FieldObjectWarp", 0X0042E960u, "anonymous_namespace::FieldObjectWarp(cmvm::CmContext*,const char*,const char*)", CommandFamily::PresentationField},
    {"ev::FieldObjectFadeOut", 0X0042F594u, "anonymous_namespace::FieldObjectFadeOut(cmvm::CmContext*,const char*,int)", CommandFamily::PresentationField},
    {"ev::FieldObjectPlayAnime", 0X003AD7FCu, "anonymous_namespace::FieldObjectPlayAnime(cmvm::CmContext*,const char*,const char*)", CommandFamily::PresentationField},
    {"ev::FieldObjectPlayEffect", 0X003ADC28u, "anonymous_namespace::FieldObjectPlayEffect(cmvm::CmContext*,const char*,const char*,const char*)", CommandFamily::PresentationField},
    {"ev::UnitRescue", 0X003A7504u, "anonymous_namespace::UnitRescue(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::UnitRescueAll", 0X003A8FBCu, "anonymous_namespace::UnitRescueAll(cmvm::CmContext*)", CommandFamily::UnitForce},
    {"ev::LilithDie", 0X003B0E08u, "anonymous_namespace::LilithDie(cmvm::CmContext*)", CommandFamily::AiMap},
    {"ev::EpithetUnlock", 0X003A8AB4u, "anonymous_namespace::EpithetUnlock(cmvm::CmContext*,int)", CommandFamily::UnitForce},
    {"ev::AnnaMessageSet", 0X003A9274u, "anonymous_namespace::AnnaMessageSet(cmvm::CmContext*,const char*)", CommandFamily::InventorySocial},
    {"ev::AnnaMessageClr", 0X003A9260u, "anonymous_namespace::AnnaMessageClr(cmvm::CmContext*)", CommandFamily::InventorySocial},
    {"ev::BandOpen", 0X00422A80u, "anonymous_namespace::BandOpen(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::BandClose", 0X00423CD0u, "anonymous_namespace::BandClose(cmvm::CmContext*)", CommandFamily::PresentationField},
    {"ev::CrossFade", 0X003B0CECu, "anonymous_namespace::CrossFade(cmvm::CmContext*,int)", CommandFamily::PresentationField},
    {"ev::ContentsGetFlag", 0X003A9D30u, "anonymous_namespace::ContentsGetFlag(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::ContentsSetFlag", 0X003A9D54u, "anonymous_namespace::ContentsSetFlag(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::ContentsClrFlag", 0X003A9D00u, "anonymous_namespace::ContentsClrFlag(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::ContentsGetIndex", 0X003AAF10u, "anonymous_namespace::ContentsGetIndex(cmvm::CmContext*)", CommandFamily::Core},
    {"ev::ContentsGetElapse", 0X003AB75Cu, "anonymous_namespace::ContentsGetElapse(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::ContentsUpdateTime", 0X003AC2FCu, "anonymous_namespace::ContentsUpdateTime(cmvm::CmContext*,int)", CommandFamily::Core},
    {"ev::ComebackCastle", 0X003A9330u, "anonymous_namespace::ComebackCastle(cmvm::CmContext*)", CommandFamily::InventorySocial},
    {"ev::AmiiboUpdate", 0X003A7F20u, "anonymous_namespace::AmiiboUpdate(cmvm::CmContext*,int)", CommandFamily::InventorySocial},
};
} // namespace

const CommandSpec* GetCommandSpecs() { return kCommandSpecs; }
std::size_t GetCommandSpecCount() { return sizeof(kCommandSpecs) / sizeof(kCommandSpecs[0]); }

const CommandSpec* FindCommandSpec(std::string_view command) {
    for (const auto& spec : kCommandSpecs) {
        if (command == spec.command) return &spec;
    }
    return nullptr;
}

NativeWord InvokeNative(
    NativeCommandRuntime& runtime,
    std::string_view command,
    cmvm::CmContext* context,
    const NativeWord* args,
    std::size_t argc
) {
    NativeWord typed_result = 0;
    if (runtime.typed && TryInvokeTyped(*runtime.typed, command, context, args, argc, typed_result)) {
        return typed_result;
    }
    const auto* spec = FindCommandSpec(command);
    if (!spec || !runtime.invoke) return 0;
    return runtime.invoke(runtime.user, *spec, context, args, argc);
}
} // namespace fates::event::native
