#pragma once
#include "fates/battle/battle_types.hpp"
class BattleUnit {
public:
    void UpdateCameraFrustumVisibility();
    void DeleteHair();
    void DeleteHead();
    void SetVisible(int a0, bool a1);
    void ConfrontDir();
    void CreateMagic(const char* a0, int a1);
    void ParticleMan(const char* a0);
    void ResetOnSkip();
    void WaitLoading();
    void CreateEffect(const char* a0, const nn::math::MTX34* a1, int a2);
    void PlayFootStep(const char* a0);
    void PlayWinVoice(const BattlePhase* a0);
    void SetTargetDir(const nn::math::VEC3& a0);
    void SetTimeSpace(TimeSpace::Type a0);
    void UpdateTarget(const nn::math::VEC3& a0);
    const nn::math::MTX34* FindBoneMtxPtr(const char* a0);
    void PlayDeathVoice();
    void PlayMaterialSE(const char* a0);
    void PlayThankVoice();
    void SetMagicMissed();
    void Tick_PreUpdate();
    void PlayDamageVoice(const BattlePhase* a0);
    void Tick_PostUpdate();
    void CreateColorFader(int a0, int a1, int a2, int a3, int a4);
    void CreateColorFader(int a0, int a1, int a2, int a3, int a4, int a5);
    void SetLocalTimeRate(float a0);
    void CreateChantEffect();
    void ExitSegmentRepeat(bool a0);
    AnimObj* GetPrimaryAnimObj();
    void CreateShutterFader(float a0, float a1, float a2);
    void CreateStealthFader(float a0, float a1, float a2);
    void SetInitialLocation(const nn::math::VEC3& a0, const nn::math::VEC3& a1);
    void SetMaterialEmotion(int a0);
    void SetOpMatVisibility(bool a0);
    void SetVisibleFromView(int a0, bool a1);
    void Tick_SignalExecute();
    void AttachShopAccessory(int a0);
    void DeleteBodyColliders();
    void DetachShopAccessory(int a0, int a1);
    void SetInitialDirection();
    void SetMaterialAddColor(const nw::ut::Color8& a0);
    void SetWeaponVisibility(bool a0);
    void UpdateTargetToEnemy();
    void CreateFootStepEffect(const char* a0);
    void SetMaterialHairColor(const nw::ut::Color8& a0);
    void SetMaterialMultColor(const Color8& a0);
    void SetMaterialSkinColor(const nw::ut::Color8& a0);
    void ChangeMagicTargetSide(int a0);
    void CreateClothSimulation();
    void DeleteClothSimulation();
    AnimObj* GetPrimaryRideAnimObj();
    void ReplaceBodyToSwimwear();
    void SetMaterialClothDamage(int a0);
    void SetMaterialEyePosition(const nn::math::VEC2& a0);
    void CalcRootAnimDisplacement(float& a0, float& a1, float& a2);
    void CreateTemplateColorFader(int a0);
    void CreateFootStepEffectHuman(const char* a0);
    void CreateUserDataParticleMan();
    void PlayAnimForceDirectEndPose(AnimClip::Type a0);
    void ChangeToBeast();
    void Setup();
    void SetName(const char* a0);
    void PlayAnim(const char* a0);
    void PlayAnim(AnimClip::Type a0);
    void Retarget();
    void LoadAsync(BattleUnitResName& a0);
    void MakeDirty(const BattlePhase* a0);
    void PlayVoice(const char* a0);
    void Stabilize();
    void SyncWaste();
    void UpdateDir();
    void UpdatePos();
    BattleUnit(SceneSystem* a0, int a1);
    ~BattleUnit();
    const BattleUnitResName* GetResName() const;
    nn::math::VEC3 GetFocusPos() const;
    float GetTimeRate() const;
    AnimClip::Type GetReadyAnim() const;
    int GetDeathLevel() const;
    const BattleUnitParams* GetUnitParams() const;
    bool IsAnimFinished() const;
    BattleUnit* OpponentPartner() const;
    nn::math::VEC3 CalcDualChildPos(VEC2XZ& a0, VEC2XZ& a1, const VEC2XZ& a2, const VEC2XZ& a3, float a4) const;
    int GetMaterialEmotion() const;
    std::uint8_t GetMaterialOpacity() const;
    AnimClip::Type GetBattleInitialAnim() const;
    nn::math::VEC3 GetActiveHandSlashVec(nn::math::VEC3& a0, nn::math::VEC3& a1, bool a2) const;
    nn::math::VEC2 GetMaterialEyePosition() const;
    bool IsLeftSideOnScreenSpace() const;
    int FindNamedActorAndBoneIndex(const char* a0, int& a1) const;
    const char* GetName() const;
    bool IsNamed(const char* a0) const;
    BattleUnit* Partner() const;
    AABB CalcAABB() const;
    BattleUnit* Opponent() const;
    void AreaClamp(VEC2XZ& a0, float a1) const;
    void AreaClamp(nn::math::VEC3& a0, float a1) const;
    bool IsStealth() const;
};
