#include "fates/event/backend/backend_spine.hpp"
#include <algorithm>

namespace fates::event::backend {
namespace {
constexpr BackendSpec kSpecs[] = {
    {"GameUserData__Get", 0x001B3AFCu, "GameUserData::Get", BackendFamily::CoreState, 53},
    {"anonymous_namespace__EventDialogItem__EventDialogItem", 0x003A9E50u, "anonymous_namespace::EventDialogItem::EventDialogItem", BackendFamily::ProcessUi, 39},
    {"Map__Get", 0x00342574u, "Map::Get", BackendFamily::MapField, 32},
    {"GameSkip__IsBlackOut", 0x004EB4D8u, "GameSkip::IsBlackOut", BackendFamily::CoreState, 22},
    {"GameSkip__IsSkip", 0x004EB830u, "GameSkip::IsSkip", BackendFamily::CoreState, 22},
    {"ProcInst__Create", 0x0010A1F4u, "ProcInst::Create", BackendFamily::ProcessUi, 11},
    {"VariableManager__Set", 0x001E800Cu, "VariableManager::Set", BackendFamily::CoreState, 10},
    {"BasicMenu__Create", 0x004FA880u, "BasicMenu::Create", BackendFamily::ProcessUi, 10},
    {"BasicMenu__SetText", 0x004FAFACu, "BasicMenu::SetText", BackendFamily::ProcessUi, 10},
    {"anonymous_namespace__EventDialog__EventDialog", 0x003A79ECu, "anonymous_namespace::EventDialog::EventDialog", BackendFamily::ProcessUi, 9},
    {"FieldWorld__FindObject", 0x00177A3Cu, "FieldWorld::FindObject", BackendFamily::MapField, 7},
    {"Sound__IsEnableBGMCommand", 0x0041FB28u, "Sound::IsEnableBGMCommand", BackendFamily::Presentation, 6},
    {"Sound__EnableBGMCommand", 0x0041FAB0u, "Sound::EnableBGMCommand", BackendFamily::Presentation, 6},
    {"Transporter__Get", 0x001A744Cu, "Transporter::Get", BackendFamily::GameplayData, 5},
    {"GameMessage__CreateBind", 0x0019A4B4u, "GameMessage::CreateBind", BackendFamily::ProcessUi, 5},
    {"Sound__SetEnableBGMCommand", 0x0041FB60u, "Sound::SetEnableBGMCommand", BackendFamily::Presentation, 5},
    {"ChapterSequence__GetInstance", 0x001DA0D8u, "ChapterSequence::GetInstance", BackendFamily::CoreState, 4},
    {"Fade__IsActive", 0x003CF6ACu, "Fade::IsActive", BackendFamily::Presentation, 4},
    {"FieldWorld__GetHeightMap", 0x00177D58u, "FieldWorld::GetHeightMap", BackendFamily::MapField, 4},
    {"GameMessage__SetGameSkipDisable", 0x0019A9C0u, "GameMessage::SetGameSkipDisable", BackendFamily::ProcessUi, 4},
    {"GameHandle__GameHandle_2", 0x0017BD60u, "GameHandle::GameHandle_2", BackendFamily::Infrastructure, 4},
    {"ProcGameInfo__SetUnit", 0x001BBE40u, "ProcGameInfo::SetUnit", BackendFamily::GameplayData, 3},
    {"Transporter__Add", 0x001A7050u, "Transporter::Add", BackendFamily::GameplayData, 3},
    {"HeightMap__GetMapHeight", 0x00548A90u, "HeightMap::GetMapHeight", BackendFamily::MapField, 3},
    {"Castle__Get", 0x0044544Cu, "Castle::Get", BackendFamily::Castle, 3},
    {"FieldWorld__GetScene", 0x00178298u, "FieldWorld::GetScene", BackendFamily::MapField, 3},
    {"map__Draw__GetInstance", 0x00388B88u, "map::Draw::GetInstance", BackendFamily::MapField, 3},
    {"FieldWorld__GetParam", 0x00178280u, "FieldWorld::GetParam", BackendFamily::MapField, 3},
    {"FlagNameManager__EntryGlobal", 0x001E086Cu, "FlagNameManager::EntryGlobal", BackendFamily::CoreState, 2},
    {"FlagNameManager__Entry", 0x001E08ACu, "FlagNameManager::Entry", BackendFamily::CoreState, 2},
    {"FlagManager__Set", 0x00199D50u, "FlagManager::Set", BackendFamily::CoreState, 2},
    {"ChapterSequence__GetStatus", 0x001DBE1Cu, "ChapterSequence::GetStatus", BackendFamily::CoreState, 2},
    {"VariableManager__Set_2", 0x001E8074u, "VariableManager::Set_2", BackendFamily::CoreState, 2},
    {"VariableManager__Add", 0x001E7F74u, "VariableManager::Add", BackendFamily::CoreState, 2},
    {"Random__GetValue_2", 0x0044AE14u, "Random::GetValue_2", BackendFamily::CoreState, 2},
    {"Fade__FadeIn", 0x0033A2C0u, "Fade::FadeIn", BackendFamily::Presentation, 2},
    {"Fade__FadeOut", 0x003CF60Cu, "Fade::FadeOut", BackendFamily::Presentation, 2},
    {"ProcTalkManager__CreateInstanceBind", 0x001E56A0u, "ProcTalkManager::CreateInstanceBind", BackendFamily::ProcessUi, 2},
    {"ProcTalkManager__Initialize", 0x001E4830u, "ProcTalkManager::Initialize", BackendFamily::ProcessUi, 2},
    {"ProcInst__ProcInst", 0x0010A2A8u, "ProcInst::ProcInst", BackendFamily::ProcessUi, 2},
    {"Spot__Get", 0x003D30A4u, "Spot::Get", BackendFamily::MapField, 2},
    {"Spot__GetData", 0x003D3104u, "Spot::GetData", BackendFamily::MapField, 2},
    {"Map__Load", 0x003426F4u, "Map::Load", BackendFamily::MapField, 2},
    {"ItemSkill__Get", 0x00500CB0u, "ItemSkill::Get", BackendFamily::GameplayData, 2},
    {"ProcGameInfo__GetUnit", 0x001BBE20u, "ProcGameInfo::GetUnit", BackendFamily::GameplayData, 2},
    {"map__sound__Se__DangerOn", 0x00398268u, "map::sound::Se::DangerOn", BackendFamily::Presentation, 2},
    {"map__sound__Se__DangerOff", 0x003982C0u, "map::sound::Se::DangerOff", BackendFamily::Presentation, 2},
    {"Transporter__Delete", 0x001A74FCu, "Transporter::Delete", BackendFamily::GameplayData, 2},
    {"FieldWorld__UpdateRange_2", 0x00177C04u, "FieldWorld::UpdateRange_2", BackendFamily::MapField, 2},
    {"GameFont__AddItem", 0x004E72F0u, "GameFont::AddItem", BackendFamily::ProcessUi, 2},
    {"map__sound__Se__ItemGain", 0x00398284u, "map::sound::Se::ItemGain", BackendFamily::Presentation, 2},
    {"castle__Accessory__AddAccessory", 0x00499AE8u, "castle::Accessory::AddAccessory", BackendFamily::Castle, 2},
    {"Movie__GetProc", 0x0041F12Cu, "Movie::GetProc", BackendFamily::Presentation, 2},
    {"Sound__BGMStop", 0x00420244u, "Sound::BGMStop", BackendFamily::Presentation, 2},
    {"FieldObject__SetState", 0x001985D8u, "FieldObject::SetState", BackendFamily::MapField, 2},
    {"GameLinkData__Dump", 0x0050BB84u, "GameLinkData::Dump", BackendFamily::CoreState, 2},
    {"GameConfigData__IsSpeedFast", 0x0050AA68u, "GameConfigData::IsSpeedFast", BackendFamily::CoreState, 1},
    {"FlagManager__Clr", 0x00199CD4u, "FlagManager::Clr", BackendFamily::CoreState, 1},
    {"GameSkip__Trigger", 0x004EB9FCu, "GameSkip::Trigger", BackendFamily::CoreState, 1},
    {"GameSkipSequenceHelper__EscapeSkip", 0x0021DCC0u, "GameSkipSequenceHelper::EscapeSkip", BackendFamily::CoreState, 1},
    {"GameSkipSequenceHelper__EnableSkip", 0x0021DC9Cu, "GameSkipSequenceHelper::EnableSkip", BackendFamily::CoreState, 1},
    {"GameSkipSequenceHelper__DisableSkip", 0x0021DCF8u, "GameSkipSequenceHelper::DisableSkip", BackendFamily::CoreState, 1},
    {"GameSkip__IsDisable", 0x004EBAD0u, "GameSkip::IsDisable", BackendFamily::CoreState, 1},
    {"GameDialog__GameDialog", 0x0017A500u, "GameDialog::GameDialog", BackendFamily::ProcessUi, 1},
    {"VariableManager__Get", 0x0050BCCCu, "VariableManager::Get", BackendFamily::CoreState, 1},
    {"ContentsUtil__IsOwnedRoute", 0x001AC9B8u, "ContentsUtil::IsOwnedRoute", BackendFamily::CoreState, 1},
    {"BasicMenu__SetSelectFromIndexAsPossible", 0x004F96F8u, "BasicMenu::SetSelectFromIndexAsPossible", BackendFamily::ProcessUi, 1},
    {"ProcInst__Create_2", 0x004EE0BCu, "ProcInst::Create_2", BackendFamily::ProcessUi, 1},
    {"ProcInst__Delete", 0x0011D300u, "ProcInst::Delete", BackendFamily::ProcessUi, 1},
    {"castle__CastleWorld__Initialize", 0x0044F5CCu, "castle::CastleWorld::Initialize", BackendFamily::Castle, 1},
    {"Map__Free", 0x00342584u, "Map::Free", BackendFamily::MapField, 1},
    {"castle__CastleWorld__Finalize", 0x0044FD24u, "castle::CastleWorld::Finalize", BackendFamily::Castle, 1},
    {"map__Draw__Create", 0x00388CB4u, "map::Draw::Create", BackendFamily::MapField, 1},
    {"map__Draw__Delete", 0x00388DC0u, "map::Draw::Delete", BackendFamily::MapField, 1},
    {"Proc__ResDelayBind", 0x003D2940u, "Proc::ResDelayBind", BackendFamily::Infrastructure, 1},
    {"JobCategory__Get", 0x0019B9CCu, "JobCategory::Get", BackendFamily::GameplayData, 1},
    {"map__ItemHelper__Rod__GetRescuePosition", 0x0034A32Cu, "map::ItemHelper::Rod::GetRescuePosition", BackendFamily::MapField, 1},
    {"unit__Enhance__AddWeakness", 0x0041B1CCu, "unit::Enhance::AddWeakness", BackendFamily::GameplayData, 1},
    {"unit__Enhance__MergeWeakness", 0x0041B308u, "unit::Enhance::MergeWeakness", BackendFamily::GameplayData, 1},
    {"Fade__IsBlackOut", 0x003CF4D8u, "Fade::IsBlackOut", BackendFamily::Presentation, 1},
    {"unit__AI__operator", 0x004192F4u, "unit::AI::operator", BackendFamily::GameplayData, 1},
    {"UnitActor__SetMotion", 0x00504D14u, "UnitActor::SetMotion", BackendFamily::GameplayData, 1},
    {"UnitIcon__SetIcon_5", 0x004F53B4u, "UnitIcon::SetIcon_5", BackendFamily::GameplayData, 1},
    {"AIDesc__Get", 0x004432A8u, "AIDesc::Get", BackendFamily::GameplayData, 1},
    {"AIValue__SetValue", 0x004D6C8Cu, "AIValue::SetValue", BackendFamily::GameplayData, 1},
    {"Transporter__SetInvalidRefine", 0x001A6EB8u, "Transporter::SetInvalidRefine", BackendFamily::GameplayData, 1},
    {"FieldWorld__UpdateRange_3", 0x00177C20u, "FieldWorld::UpdateRange_3", BackendFamily::MapField, 1},
    {"anonymous_namespace__GimmickMedicineImpl", 0x003AC8E4u, "anonymous_namespace::GimmickMedicineImpl", BackendFamily::GameplayData, 1},
    {"Random__Initialize", 0x0044ABC4u, "Random::Initialize", BackendFamily::CoreState, 1},
    {"map__Effect__Create_3", 0x0039FAECu, "map::Effect::Create_3", BackendFamily::MapField, 1},
    {"GameHandle__GameHandle", 0x0017BD20u, "GameHandle::GameHandle", BackendFamily::Infrastructure, 1},
    {"FlagManagerNoName__Set", 0x00202BDCu, "FlagManagerNoName::Set", BackendFamily::CoreState, 1},
    {"map__NoticeWindow__Create", 0x0034D08Cu, "map::NoticeWindow::Create", BackendFamily::ProcessUi, 1},
    {"map__Intermediate__Tutorial__Create", 0x0034CC64u, "map::Intermediate::Tutorial::Create", BackendFamily::ProcessUi, 1},
    {"FlagManagerNoName__SetAll", 0x0012A0C0u, "FlagManagerNoName::SetAll", BackendFamily::CoreState, 1},
    {"map__Draw__SuspendBind", 0x00388B98u, "map::Draw::SuspendBind", BackendFamily::MapField, 1},
    {"map__Draw__ResumeBind", 0x00388A80u, "map::Draw::ResumeBind", BackendFamily::MapField, 1},
    {"Movie__CreateBind", 0x0041EE54u, "Movie::CreateBind", BackendFamily::Presentation, 1},
    {"Movie__Create", 0x0041F0B8u, "Movie::Create", BackendFamily::Presentation, 1},
    {"Movie__IsPaused", 0x0041F13Cu, "Movie::IsPaused", BackendFamily::Presentation, 1},
    {"Sound__BGMPlay", 0x004201A0u, "Sound::BGMPlay", BackendFamily::Presentation, 1},
    {"Sound__BGMTrackVolume", 0x0041F730u, "Sound::BGMTrackVolume", BackendFamily::Presentation, 1},
    {"Sound__RBGMPlay", 0x00420418u, "Sound::RBGMPlay", BackendFamily::Presentation, 1},
    {"Sound__RBGMStop", 0x00420500u, "Sound::RBGMStop", BackendFamily::Presentation, 1},
    {"Sound__RBGMEffect", 0x0041F334u, "Sound::RBGMEffect", BackendFamily::Presentation, 1},
    {"Sound__BGMVolume", 0x00420858u, "Sound::BGMVolume", BackendFamily::Presentation, 1},
    {"map__sound__Bgm__UpdateBGM", 0x00399188u, "map::sound::Bgm::UpdateBGM", BackendFamily::Presentation, 1},
    {"map__sound__Bgm__Map__Resume", 0x00398FBCu, "map::sound::Bgm::Map::Resume", BackendFamily::Presentation, 1},
    {"Sound__SEPlay", 0x004200FCu, "Sound::SEPlay", BackendFamily::Presentation, 1},
    {"HeightMap__GetHeight", 0x0054931Cu, "HeightMap::GetHeight", BackendFamily::MapField, 1},
    {"Sound3D__Play", 0x004E01E8u, "Sound3D::Play", BackendFamily::Presentation, 1},
    {"Sound__LSEPlay", 0x00420318u, "Sound::LSEPlay", BackendFamily::Presentation, 1},
    {"Sound__Voice", 0x0041FFE4u, "Sound::Voice", BackendFamily::Presentation, 1},
    {"Sound__EnvStop", 0x004202FCu, "Sound::EnvStop", BackendFamily::Presentation, 1},
    {"Sound__EnvPlay", 0x0042028Cu, "Sound::EnvPlay", BackendFamily::Presentation, 1},
    {"castle__SpotSelectSequence__MoveBind", 0x0045CE0Cu, "castle::SpotSelectSequence::MoveBind", BackendFamily::Castle, 1},
    {"FieldObject__SetVisible", 0x00196F8Cu, "FieldObject::SetVisible", BackendFamily::MapField, 1},
    {"FieldObject__SetEscape", 0x001988B8u, "FieldObject::SetEscape", BackendFamily::MapField, 1},
    {"FieldWorld__CreateObject", 0x00177CF0u, "FieldWorld::CreateObject", BackendFamily::MapField, 1},
    {"FieldObject__SetDispos", 0x00198874u, "FieldObject::SetDispos", BackendFamily::MapField, 1},
    {"FieldWorld__DeleteObject", 0x00177D08u, "FieldWorld::DeleteObject", BackendFamily::MapField, 1},
    {"FieldObject__PlayAnime", 0x00198810u, "FieldObject::PlayAnime", BackendFamily::MapField, 1},
    {"FieldObject__GetLocatorIndex", 0x00508288u, "FieldObject::GetLocatorIndex", BackendFamily::MapField, 1},
    {"FieldObject__GetLocatorPos_2", 0x0050821Cu, "FieldObject::GetLocatorPos_2", BackendFamily::MapField, 1},
    {"GameLinkGlobalData__Dump", 0x0050BB18u, "GameLinkGlobalData::Dump", BackendFamily::CoreState, 1},
    {"DeliveryMessage__SetMessage", 0x001DE188u, "DeliveryMessage::SetMessage", BackendFamily::CoreState, 1},
    {"DeliveryMessage__Reset", 0x001DE1E4u, "DeliveryMessage::Reset", BackendFamily::CoreState, 1},
    {"ContentsLocal__GetElapse", 0x0050A314u, "ContentsLocal::GetElapse", BackendFamily::CoreState, 1},
    {"ContentsLocal__UpdateTime", 0x001C7124u, "ContentsLocal::UpdateTime", BackendFamily::CoreState, 1},
    {"ContentsLocal__Dump", 0x0050A300u, "ContentsLocal::Dump", BackendFamily::CoreState, 1},
    {"castle__AmiiboSequence__UpdateBind", 0x004542C8u, "castle::AmiiboSequence::UpdateBind", BackendFamily::Castle, 1},
};
}
const BackendSpec* GetBackendSpecs() { return kSpecs; }
std::size_t GetBackendSpecCount() { return sizeof(kSpecs) / sizeof(kSpecs[0]); }
const BackendSpec* FindBackendSpec(std::uint32_t retail_address) {
    const auto* first = kSpecs; const auto* last = kSpecs + GetBackendSpecCount();
    const auto it = std::find_if(first, last, [retail_address](const BackendSpec& s) { return s.retail_address == retail_address; });
    return it == last ? nullptr : it;
}
BackendWord InvokeBackend(BackendRuntime& runtime, std::uint32_t retail_address, const BackendWord* args, std::size_t argc) {
    const BackendSpec* spec = FindBackendSpec(retail_address);
    if (spec == nullptr || runtime.invoke == nullptr) return 0;
    return runtime.invoke(runtime.user, *spec, args, argc);
}
} // namespace fates::event::backend
