#include "fates/event/event.hpp"
namespace event {
namespace {
constexpr CommandBinding kBindings[] = {
    {"ev::Warning", 0x003B06C4u, "anonymous_namespace::Warning(cmvm::CmContext*,const char*)"},
    {"ev::ArgsGetInt", 0x00534C54u, "anonymous_namespace::ArgsGetInt(cmvm::CmContext*,int)"},
    {"ev::ArgsGetString", 0x00534C2Cu, "anonymous_namespace::ArgsGetString(cmvm::CmContext*,int)"},
    {"ev::TimeGetSpeed", 0x003A8200u, "anonymous_namespace::TimeGetSpeed(cmvm::CmContext*)"},
    {"ev::TimeGetConfigSpeed", 0x003AC37Cu, "anonymous_namespace::TimeGetConfigSpeed(cmvm::CmContext*)"},
    {"ev::TimeMSecToFrame", 0x003AA92Cu, "anonymous_namespace::TimeMSecToFrame(cmvm::CmContext*,int)"},
    {"ev::TimeFrameToMSec", 0x003AA90Cu, "anonymous_namespace::TimeFrameToMSec(cmvm::CmContext*,int)"},
    {"ev::FlagEntryGlobal", 0x003A9ED4u, "anonymous_namespace::FlagEntryGlobal(cmvm::CmContext*,const char*)"},
    {"ev::FlagEntry", 0x003B0D18u, "anonymous_namespace::FlagEntry(cmvm::CmContext*,const char*)"},
    {"ev::FlagGet", 0x005084ECu, "anonymous_namespace::FlagGet(cmvm::CmContext*,const char*)"},
    {"ev::FlagSet", 0x003B0624u, "anonymous_namespace::FlagSet(cmvm::CmContext*,const char*)"},
    {"ev::FlagClr", 0x003B05E8u, "anonymous_namespace::FlagClr(cmvm::CmContext*,const char*)"},
    {"ev::VariableEntryGlobal", 0x003AD680u, "anonymous_namespace::VariableEntryGlobal(cmvm::CmContext*,const char*,int)"},
    {"ev::VariableEntry", 0x003A911Cu, "anonymous_namespace::VariableEntry(cmvm::CmContext*,const char*,int)"},
    {"ev::VariableGet", 0x0050BCB0u, "anonymous_namespace::VariableGet(cmvm::CmContext*,const char*)"},
    {"ev::VariableSet", 0x001E7FE8u, "anonymous_namespace::VariableSet(cmvm::CmContext*,const char*,int)"},
    {"ev::VariableAdd", 0x001E7F50u, "anonymous_namespace::VariableAdd(cmvm::CmContext*,const char*,int)"},
    {"ev::VariableInc", 0x003A7E78u, "anonymous_namespace::VariableInc(cmvm::CmContext*,const char*)"},
    {"ev::VariableDec", 0x003A7E58u, "anonymous_namespace::VariableDec(cmvm::CmContext*,const char*)"},
    {"ev::RandomGetGame", 0x003A8BC4u, "anonymous_namespace::RandomGetGame(cmvm::CmContext*)"},
    {"ev::RandomGetSystem", 0x003AA868u, "anonymous_namespace::RandomGetSystem(cmvm::CmContext*)"},
    {"ev::SkipTrigger", 0x003A7AF8u, "anonymous_namespace::SkipTrigger(cmvm::CmContext*)"},
    {"ev::SkipEscape", 0x003A7224u, "anonymous_namespace::SkipEscape(cmvm::CmContext*)"},
    {"ev::SkipEnable", 0x003A71FCu, "anonymous_namespace::SkipEnable(cmvm::CmContext*)"},
    {"ev::SkipDisable", 0x003A7AD0u, "anonymous_namespace::SkipDisable(cmvm::CmContext*)"},
    {"ev::SkipIsActive", 0x003A81F0u, "anonymous_namespace::SkipIsActive(cmvm::CmContext*)"},
    {"ev::SkipIsDisable", 0x003A8BD0u, "anonymous_namespace::SkipIsDisable(cmvm::CmContext*)"},
    {"ev::FadeIn", 0x003AF594u, "anonymous_namespace::FadeIn(cmvm::CmContext*,int,int,int)"},
    {"ev::FadeOut", 0x003B04ECu, "anonymous_namespace::FadeOut(cmvm::CmContext*,int,int,int)"},
    {"ev::FadeIsWait", 0x003A7110u, "anonymous_namespace::FadeIsWait(cmvm::CmContext*)"},
    {"ev::Talk", 0x003AF36Cu, "anonymous_namespace::Talk(cmvm::CmContext*,const char*)"},
    {"ev::TalkNoShadowFrame", 0x003ABC48u, "anonymous_namespace::TalkNoShadowFrame(cmvm::CmContext*,const char*)"},
    {"ev::Dialog1", 0x003AF6E8u, "anonymous_namespace::Dialog1(cmvm::CmContext*,const char*,const char*)"},
    {"ev::Dialog2", 0x003AF7F0u, "anonymous_namespace::Dialog2(cmvm::CmContext*,const char*,const char*,const char*)"},
    {"ev::Dialog3", 0x003AF92Cu, "anonymous_namespace::Dialog3(cmvm::CmContext*,const char*,const char*,const char*,const char*)"},
    {"ev::Dialog4", 0x003AFA9Cu, "anonymous_namespace::Dialog4(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*)"},
    {"ev::Dialog5", 0x003AFC40u, "anonymous_namespace::Dialog5(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*)"},
    {"ev::Dialog6", 0x003AFE14u, "anonymous_namespace::Dialog6(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*,const char*)"},
    {"ev::Dialog7", 0x003B0018u, "anonymous_namespace::Dialog7(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*)"},
    {"ev::Dialog8", 0x003B0248u, "anonymous_namespace::Dialog8(cmvm::CmContext*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*)"},
    {"ev::DialogYesNo", 0x003A785Cu, "anonymous_namespace::DialogYesNo(cmvm::CmContext*,const char*)"},
    {"ev::DialogGetResult", 0x003A9D84u, "anonymous_namespace::DialogGetResult(cmvm::CmContext*)"},
    {"ev::RouteBranchDialog", 0x003ABA98u, "anonymous_namespace::RouteBranchDialog(cmvm::CmContext*,const char*,const char*,const char*,const char*,int)"},
    {"ev::RouteBranchBegin", 0x003AB06Cu, "anonymous_namespace::RouteBranchBegin(cmvm::CmContext*)"},
    {"ev::RouteBranchEnd", 0x003A9590u, "anonymous_namespace::RouteBranchEnd(cmvm::CmContext*)"},
    {"ev::ChapterGetName", 0x003A92E8u, "anonymous_namespace::ChapterGetName(cmvm::CmContext*)"},
    {"ev::ChapterGetEncountName", 0x003ADBA8u, "anonymous_namespace::ChapterGetEncountName(cmvm::CmContext*)"},
    {"ev::ChapterGetVersusName", 0x003AD770u, "anonymous_namespace::ChapterGetVersusName(cmvm::CmContext*)"},
    {"ev::ChapterIsCID", 0x003A7F44u, "anonymous_namespace::ChapterIsCID(cmvm::CmContext*,const char*)"},
    {"ev::ChapterSetWinRuleBreakdown", 0x003AED04u, "anonymous_namespace::ChapterSetWinRuleBreakdown(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetWinRuleDestroyBoss", 0x003AEF44u, "anonymous_namespace::ChapterSetWinRuleDestroyBoss(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetWinRuleEscape", 0x003AE718u, "anonymous_namespace::ChapterSetWinRuleEscape(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetWinRuleEscapeHero", 0x003AEEECu, "anonymous_namespace::ChapterSetWinRuleEscapeHero(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetWinRuleEnemyNumberLessThanOrEqualTo", 0x003AF354u, "anonymous_namespace::ChapterSetWinRuleEnemyNumberLessThanOrEqualTo(cmvm::CmContext*,int)"},
    {"ev::ChapterSetWinRuleLimitTurn", 0x003AED30u, "anonymous_namespace::ChapterSetWinRuleLimitTurn(cmvm::CmContext*,int)"},
    {"ev::ChapterSetWinRuleMessageIndex", 0x003AEFECu, "anonymous_namespace::ChapterSetWinRuleMessageIndex(cmvm::CmContext*,int)"},
    {"ev::ChapterShowWinRuleTelopImpl", 0x00361890u, "anonymous_namespace::ChapterShowWinRuleTelopImpl(cmvm::CmContext*)"},
    {"ev::ChapterGetWinLoseResult", 0x003AE6E8u, "anonymous_namespace::ChapterGetWinLoseResult(cmvm::CmContext*)"},
    {"ev::ChapterSetWin", 0x003A8A50u, "anonymous_namespace::ChapterSetWin(cmvm::CmContext*)"},
    {"ev::ChapterSetLose", 0x003A9310u, "anonymous_namespace::ChapterSetLose(cmvm::CmContext*)"},
    {"ev::ChapterSetTemporaryCasual", 0x003AEBE8u, "anonymous_namespace::ChapterSetTemporaryCasual(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetContinueAfterGameOver", 0x003AF198u, "anonymous_namespace::ChapterSetContinueAfterGameOver(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetSkipChapterSaveCastle", 0x003AF250u, "anonymous_namespace::ChapterSetSkipChapterSaveCastle(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetSkipSortie", 0x003AD7C8u, "anonymous_namespace::ChapterSetSkipSortie(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetInvalidSortieSaveBack", 0x003AF1F0u, "anonymous_namespace::ChapterSetInvalidSortieSaveBack(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetProhibitWarp", 0x003AE100u, "anonymous_namespace::ChapterSetProhibitWarp(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetHideSystemMenu", 0x003AE830u, "anonymous_namespace::ChapterSetHideSystemMenu(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetHideProperty", 0x003AE0B8u, "anonymous_namespace::ChapterSetHideProperty(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetHideTrade", 0x003AC7F4u, "anonymous_namespace::ChapterSetHideTrade(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetHideDouble", 0x003AD79Cu, "anonymous_namespace::ChapterSetHideDouble(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetHideAI", 0x003AAEE4u, "anonymous_namespace::ChapterSetHideAI(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetHideHpGauge", 0x003ADBE8u, "anonymous_namespace::ChapterSetHideHpGauge(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetExpMode", 0x003AB744u, "anonymous_namespace::ChapterSetExpMode(cmvm::CmContext*,int)"},
    {"ev::ChapterSetInvalidPhoenix", 0x003AE85Cu, "anonymous_namespace::ChapterSetInvalidPhoenix(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetInvalidGainDragonVein", 0x003AF1C4u, "anonymous_namespace::ChapterSetInvalidGainDragonVein(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetInvalidGainReliance", 0x003AEFC0u, "anonymous_namespace::ChapterSetInvalidGainReliance(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetInvalidTransporter", 0x003AEF18u, "anonymous_namespace::ChapterSetInvalidTransporter(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetInvalidRecordKill", 0x003AEEC0u, "anonymous_namespace::ChapterSetInvalidRecordKill(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetInvalidRecordDead", 0x003AEE94u, "anonymous_namespace::ChapterSetInvalidRecordDead(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetInvalidFixedGain", 0x003AECD8u, "anonymous_namespace::ChapterSetInvalidFixedGain(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetValiedSurrender", 0x003AEC14u, "anonymous_namespace::ChapterSetValiedSurrender(cmvm::CmContext*,bool)"},
    {"ev::ChapterAppear", 0x003A8A0Cu, "anonymous_namespace::ChapterAppear(cmvm::CmContext*,const char*)"},
    {"ev::ChapterIsCleared", 0x003AAE98u, "anonymous_namespace::ChapterIsCleared(cmvm::CmContext*,const char*)"},
    {"ev::ChapterIsCastleOffense", 0x003AE0A0u, "anonymous_namespace::ChapterIsCastleOffense(cmvm::CmContext*)"},
    {"ev::ChapterIsCastleSelfTest", 0x003AE700u, "anonymous_namespace::ChapterIsCastleSelfTest(cmvm::CmContext*)"},
    {"ev::ChapterGetTrickDragon", 0x003ADBD4u, "anonymous_namespace::ChapterGetTrickDragon(cmvm::CmContext*)"},
    {"ev::ChapterSetTrickDragon", 0x003ADC14u, "anonymous_namespace::ChapterSetTrickDragon(cmvm::CmContext*,int)"},
    {"ev::ChapterSetNotReturnMap", 0x003AE0E4u, "anonymous_namespace::ChapterSetNotReturnMap(cmvm::CmContext*)"},
    {"ev::ChapterSetEscapeEffectWarp", 0x003AECACu, "anonymous_namespace::ChapterSetEscapeEffectWarp(cmvm::CmContext*,bool)"},
    {"ev::ChapterSetResistInterferenceRod", 0x003AF224u, "anonymous_namespace::ChapterSetResistInterferenceRod(cmvm::CmContext*,bool)"},
    {"ev::MessLoad", 0x003D1EA4u, "anonymous_namespace::MessLoad(cmvm::CmContext*,const char*)"},
    {"ev::MessFree", 0x003D1E10u, "anonymous_namespace::MessFree(cmvm::CmContext*,const char*)"},
    {"ev::MessSetArgumentByMID", 0x003D1604u, "anonymous_namespace::MessSetArgumentByMID(cmvm::CmContext*,int,const char*)"},
    {"ev::MessSetArgumentByValue", 0x003D1648u, "anonymous_namespace::MessSetArgumentByValue(cmvm::CmContext*,int,int)"},
    {"ev::PersonLoad", 0x0044A800u, "anonymous_namespace::PersonLoad(cmvm::CmContext*,const char*)"},
    {"ev::PersonFree", 0x0044A768u, "anonymous_namespace::PersonFree(cmvm::CmContext*,const char*)"},
    {"ev::TerrainLoad", 0x003426D4u, "anonymous_namespace::TerrainLoad(cmvm::CmContext*,const char*)"},
    {"ev::TerrainLoadScript", 0x003ABCB8u, "anonymous_namespace::TerrainLoadScript(cmvm::CmContext*,const char*,const char*)"},
    {"ev::TerrainLoadCastle", 0x003ABC8Cu, "anonymous_namespace::TerrainLoadCastle(cmvm::CmContext*)"},
    {"ev::TerrainFree", 0x003A7B80u, "anonymous_namespace::TerrainFree(cmvm::CmContext*)"},
    {"ev::TerrainGetW", 0x003A7BD0u, "anonymous_namespace::TerrainGetW(cmvm::CmContext*)"},
    {"ev::TerrainGetH", 0x003A7BACu, "anonymous_namespace::TerrainGetH(cmvm::CmContext*)"},
    {"ev::TerrainIsOutOfPlayArea", 0x003AE294u, "anonymous_namespace::TerrainIsOutOfPlayArea(cmvm::CmContext*,int,int)"},
    {"ev::TerrainDrawBegin", 0x003AB110u, "anonymous_namespace::TerrainDrawBegin(cmvm::CmContext*)"},
    {"ev::TerrainDrawEnd", 0x003A95B8u, "anonymous_namespace::TerrainDrawEnd(cmvm::CmContext*)"},
    {"ev::DisposLoad", 0x0039ED84u, "anonymous_namespace::DisposLoad(cmvm::CmContext*,const char*)"},
    {"ev::DisposFree", 0x0039ED28u, "anonymous_namespace::DisposFree(cmvm::CmContext*)"},
    {"ev::Dispos", 0x0039DB4Cu, "anonymous_namespace::Dispos(cmvm::CmContext*,const char*,int)"},
    {"ev::DisposIsWait", 0x0039DFACu, "anonymous_namespace::DisposIsWait(cmvm::CmContext*)"},
    {"ev::ForceGetActive", 0x003A9490u, "anonymous_namespace::ForceGetActive(cmvm::CmContext*)"},
    {"ev::ForceUnitGetFirst", 0x003AB868u, "anonymous_namespace::ForceUnitGetFirst(cmvm::CmContext*,int)"},
    {"ev::ForceUnitGetNext", 0x003AAF70u, "anonymous_namespace::ForceUnitGetNext(cmvm::CmContext*,int)"},
    {"ev::ForceUnitGetCount", 0x003AB838u, "anonymous_namespace::ForceUnitGetCount(cmvm::CmContext*,int)"},
    {"ev::ForceUnitGetCountArea", 0x003ADD38u, "anonymous_namespace::ForceUnitGetCountArea(cmvm::CmContext*,int,int,int,int,int,bool)"},
    {"ev::ForceUnitTransfer", 0x003AB8A8u, "anonymous_namespace::ForceUnitTransfer(cmvm::CmContext*,int,int)"},
    {"ev::ForceUnitTransferExchange", 0x003AEC40u, "anonymous_namespace::ForceUnitTransferExchange(cmvm::CmContext*,int,int)"},
    {"ev::ForceUnitDelete", 0x003A9F10u, "anonymous_namespace::ForceUnitDelete(cmvm::CmContext*,int)"},
    {"ev::ForceUnitExpulsion", 0x003AB8A0u, "anonymous_namespace::ForceUnitExpulsion(cmvm::CmContext*,int)"},
    {"ev::UnitGetByPID", 0x003A8390u, "anonymous_namespace::UnitGetByPID(cmvm::CmContext*,const char*)"},
    {"ev::UnitGetByPIDForce", 0x003ABE24u, "anonymous_namespace::UnitGetByPIDForce(cmvm::CmContext*,const char*,int)"},
    {"ev::UnitGetByPosition", 0x003ABE80u, "anonymous_namespace::UnitGetByPosition(cmvm::CmContext*,int,int)"},
    {"ev::UnitTransferByIndex", 0x003AD280u, "anonymous_namespace::UnitTransferByIndex(cmvm::CmContext*,int,int)"},
    {"ev::UnitDeleteByIndex", 0x003ABDD0u, "anonymous_namespace::UnitDeleteByIndex(cmvm::CmContext*,int)"},
    {"ev::UnitLostByIndex", 0x003AAD10u, "anonymous_namespace::UnitLostByIndex(cmvm::CmContext*,int)"},
    {"ev::UnitExpulsionByIndex", 0x003AD278u, "anonymous_namespace::UnitExpulsionByIndex(cmvm::CmContext*,int)"},
    {"ev::UnitIsAlive", 0x003A7C80u, "anonymous_namespace::UnitIsAlive(cmvm::CmContext*,int)"},
    {"ev::UnitIsDoubleParent", 0x003AC5B0u, "anonymous_namespace::UnitIsDoubleParent(cmvm::CmContext*,int)"},
    {"ev::UnitIsDoubleChild", 0x003ABF94u, "anonymous_namespace::UnitIsDoubleChild(cmvm::CmContext*,int)"},
    {"ev::UnitSetPID", 0x003A768Cu, "anonymous_namespace::UnitSetPID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitIsPID", 0x003B0FE4u, "anonymous_namespace::UnitIsPID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitIsPIDWithGuest", 0x003AC5FCu, "anonymous_namespace::UnitIsPIDWithGuest(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitIsResidentFirstPID", 0x003AE4D0u, "anonymous_namespace::UnitIsResidentFirstPID(cmvm::CmContext*,int)"},
    {"ev::UnitIsFatherPID", 0x003AAB58u, "anonymous_namespace::UnitIsFatherPID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitIsMotherPID", 0x003AABECu, "anonymous_namespace::UnitIsMotherPID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitSetJID", 0x003A75A0u, "anonymous_namespace::UnitSetJID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitIsJID", 0x003B0F78u, "anonymous_namespace::UnitIsJID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitIsHighJob", 0x003A8DA0u, "anonymous_namespace::UnitIsHighJob(cmvm::CmContext*,int)"},
    {"ev::UnitIsJCID", 0x003A7494u, "anonymous_namespace::UnitIsJCID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitSetBID", 0x003A7550u, "anonymous_namespace::UnitSetBID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitIsBID", 0x003B0F18u, "anonymous_namespace::UnitIsBID(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitGetForce", 0x003A83C0u, "anonymous_namespace::UnitGetForce(cmvm::CmContext*,int)"},
    {"ev::UnitGetX", 0x003B0AD0u, "anonymous_namespace::UnitGetX(cmvm::CmContext*,int)"},
    {"ev::UnitGetY", 0x003B0B20u, "anonymous_namespace::UnitGetY(cmvm::CmContext*,int)"},
    {"ev::UnitSetPosition", 0x003AAD88u, "anonymous_namespace::UnitSetPosition(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitSetPositionFreeSpace", 0x003AEA74u, "anonymous_namespace::UnitSetPositionFreeSpace(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitMovePosition", 0x003AB1A4u, "anonymous_namespace::UnitMovePosition(cmvm::CmContext*,int,int,int,int)"},
    {"ev::UnitMoveSlide", 0x003A8E84u, "anonymous_namespace::UnitMoveSlide(cmvm::CmContext*,int,int,int,int)"},
    {"ev::UnitSetAlpha", 0x003A86F4u, "anonymous_namespace::UnitSetAlpha(cmvm::CmContext*,int,int)"},
    {"ev::UnitMoveAlphaDeadOut", 0x003ADA88u, "anonymous_namespace::UnitMoveAlphaDeadOut(cmvm::CmContext*,int)"},
    {"ev::UnitMoveAlphaWarpIn", 0x003AD0C0u, "anonymous_namespace::UnitMoveAlphaWarpIn(cmvm::CmContext*,int)"},
    {"ev::UnitMoveAlphaWarpOut", 0x003ADAF8u, "anonymous_namespace::UnitMoveAlphaWarpOut(cmvm::CmContext*,int)"},
    {"ev::UnitIsMoveWait", 0x003A9858u, "anonymous_namespace::UnitIsMoveWait(cmvm::CmContext*)"},
    {"ev::UnitSetDontAttack", 0x003AC208u, "anonymous_namespace::UnitSetDontAttack(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitSetDontAttackForce", 0x003AE684u, "anonymous_namespace::UnitSetDontAttackForce(cmvm::CmContext*,int,int)"},
    {"ev::UnitGetLevel", 0x003A8408u, "anonymous_namespace::UnitGetLevel(cmvm::CmContext*,int)"},
    {"ev::UnitGetInternalLevel", 0x003AD910u, "anonymous_namespace::UnitGetInternalLevel(cmvm::CmContext*,int)"},
    {"ev::UnitGetHP", 0x003B0ED4u, "anonymous_namespace::UnitGetHP(cmvm::CmContext*,int)"},
    {"ev::UnitGetMHP", 0x003A73D8u, "anonymous_namespace::UnitGetMHP(cmvm::CmContext*,int)"},
    {"ev::UnitSetHP", 0x003B105Cu, "anonymous_namespace::UnitSetHP(cmvm::CmContext*,int,int)"},
    {"ev::UnitGetCapability", 0x003ABEC0u, "anonymous_namespace::UnitGetCapability(cmvm::CmContext*,int,int,bool)"},
    {"ev::UnitSetCapability", 0x003AC1B8u, "anonymous_namespace::UnitSetCapability(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitGetMovePower", 0x0052D580u, "anonymous_namespace::UnitGetMovePower(cmvm::CmContext*,int,bool)"},
    {"ev::UnitSetMovePower", 0x003AB694u, "anonymous_namespace::UnitSetMovePower(cmvm::CmContext*,int,int)"},
    {"ev::UnitGetWeaponLevel", 0x003AC430u, "anonymous_namespace::UnitGetWeaponLevel(cmvm::CmContext*,int,int,bool)"},
    {"ev::UnitGetMarrigeUnit", 0x003AC3C0u, "anonymous_namespace::UnitGetMarrigeUnit(cmvm::CmContext*,int)"},
    {"ev::UnitGetRecordKill", 0x003ABF50u, "anonymous_namespace::UnitGetRecordKill(cmvm::CmContext*,int)"},
    {"ev::UnitItemIsExist", 0x003AAC80u, "anonymous_namespace::UnitItemIsExist(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitItemAddDirect", 0x003ABFE0u, "anonymous_namespace::UnitItemAddDirect(cmvm::CmContext*,int,const char*,bool)"},
    {"ev::UnitItemPutOff", 0x003A994Cu, "anonymous_namespace::UnitItemPutOff(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitItemPutOffAll", 0x003AC124u, "anonymous_namespace::UnitItemPutOffAll(cmvm::CmContext*,int)"},
    {"ev::UnitItemToTransporter", 0x003ADF84u, "anonymous_namespace::UnitItemToTransporter(cmvm::CmContext*,int)"},
    {"ev::UnitItemDisposalFor006", 0x003AE518u, "anonymous_namespace::UnitItemDisposalFor006(cmvm::CmContext*,int)"},
    {"ev::UnitItemEquip", 0x003A8E34u, "anonymous_namespace::UnitItemEquip(cmvm::CmContext*,int)"},
    {"ev::UnitItemEquip2", 0x003A98B4u, "anonymous_namespace::UnitItemEquip2(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitItemClearEquip", 0x003AC674u, "anonymous_namespace::UnitItemClearEquip(cmvm::CmContext*,int)"},
    {"ev::UnitItemClearDrop", 0x003AC058u, "anonymous_namespace::UnitItemClearDrop(cmvm::CmContext*,int)"},
    {"ev::UnitItemSetEndurance", 0x003AD9D4u, "anonymous_namespace::UnitItemSetEndurance(cmvm::CmContext*,int,const char*,int)"},
    {"ev::UnitItemSetInvalidRefine", 0x003AEA0Cu, "anonymous_namespace::UnitItemSetInvalidRefine(cmvm::CmContext*,int,bool)"},
    {"ev::UnitShowDanger", 0x003A9AA4u, "anonymous_namespace::UnitShowDanger(cmvm::CmContext*,int,bool)"},
    {"ev::UnitShowWholeDanger", 0x003AD1ACu, "anonymous_namespace::UnitShowWholeDanger(cmvm::CmContext*,bool)"},
    {"ev::UnitSetPrivateSkill", 0x003AD134u, "anonymous_namespace::UnitSetPrivateSkill(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitClrPrivateSkill", 0x003AD03Cu, "anonymous_namespace::UnitClrPrivateSkill(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitTstPrivateSkill", 0x003AD5E8u, "anonymous_namespace::UnitTstPrivateSkill(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitCanDragonVein", 0x003ABD8Cu, "anonymous_namespace::UnitCanDragonVein(cmvm::CmContext*,int)"},
    {"ev::UnitIsEquipSkill", 0x003AB148u, "anonymous_namespace::UnitIsEquipSkill(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitAddEquipSkill", 0x003ABCDCu, "anonymous_namespace::UnitAddEquipSkill(cmvm::CmContext*,int,const char*)"},
    {"ev::UnitDoubleOn", 0x003A8290u, "anonymous_namespace::UnitDoubleOn(cmvm::CmContext*,int,int)"},
    {"ev::UnitDoubleOff", 0x003A8CE4u, "anonymous_namespace::UnitDoubleOff(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitBackup", 0x003A734Cu, "anonymous_namespace::UnitBackup(cmvm::CmContext*,int)"},
    {"ev::UnitRestore", 0x003A7D58u, "anonymous_namespace::UnitRestore(cmvm::CmContext*,int,bool,bool)"},
    {"ev::UnitBackupDiscard", 0x003ABD34u, "anonymous_namespace::UnitBackupDiscard(cmvm::CmContext*,int)"},
    {"ev::UnitHpDamage", 0x003A844Cu, "anonymous_namespace::UnitHpDamage(cmvm::CmContext*,int,int)"},
    {"ev::UnitHpHeal", 0x003A7428u, "anonymous_namespace::UnitHpHeal(cmvm::CmContext*,int,int)"},
    {"ev::UnitIsHpEffectWait", 0x0035EAE0u, "anonymous_namespace::UnitIsHpEffectWait(cmvm::CmContext*)"},
    {"ev::UnitSetEnhance", 0x003A99E8u, "anonymous_namespace::UnitSetEnhance(cmvm::CmContext*,int,int)"},
    {"ev::UnitClrEnhance", 0x003A97FCu, "anonymous_namespace::UnitClrEnhance(cmvm::CmContext*,int,int)"},
    {"ev::UnitTstEnhance", 0x003A9BF0u, "anonymous_namespace::UnitTstEnhance(cmvm::CmContext*,int,int)"},
    {"ev::UnitGetWeakness", 0x003AAB0Cu, "anonymous_namespace::UnitGetWeakness(cmvm::CmContext*,int,int)"},
    {"ev::UnitAddWeakness", 0x003AA94Cu, "anonymous_namespace::UnitAddWeakness(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitMergeWeakness", 0x003AC164u, "anonymous_namespace::UnitMergeWeakness(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitCreateClone", 0x003AA9A0u, "anonymous_namespace::UnitCreateClone(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitIsClone", 0x003A7CC0u, "anonymous_namespace::UnitIsClone(cmvm::CmContext*,int)"},
    {"ev::UnitSetNeverSortie", 0x003AC6DCu, "anonymous_namespace::UnitSetNeverSortie(cmvm::CmContext*,int,bool)"},
    {"ev::UnitRecreate", 0x003A84B8u, "anonymous_namespace::UnitRecreate(cmvm::CmContext*,int,const char*,int)"},
    {"ev::UnitSetPhantom", 0x003A9A44u, "anonymous_namespace::UnitSetPhantom(cmvm::CmContext*,int,bool)"},
    {"ev::UnitIsPhantom", 0x003A8DE8u, "anonymous_namespace::UnitIsPhantom(cmvm::CmContext*,int)"},
    {"ev::UnitTstStatus", 0x003A90B8u, "anonymous_namespace::UnitTstStatus(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitSetStatus", 0x003A9060u, "anonymous_namespace::UnitSetStatus(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitClrStatus", 0x003A8C8Cu, "anonymous_namespace::UnitClrStatus(cmvm::CmContext*,int,int,int)"},
    {"ev::UnitIsAbleToAttack", 0x003AC4A4u, "anonymous_namespace::UnitIsAbleToAttack(cmvm::CmContext*,int)"},
    {"ev::UnitIsSleep", 0x003A7D0Cu, "anonymous_namespace::UnitIsSleep(cmvm::CmContext*,int)"},
    {"ev::UnitSetMotion", 0x003A900Cu, "anonymous_namespace::UnitSetMotion(cmvm::CmContext*,int,int)"},
    {"ev::UnitGetRelianceLevel", 0x003AD958u, "anonymous_namespace::UnitGetRelianceLevel(cmvm::CmContext*,int,int)"},
    {"ev::UnitSetInvalidEternal", 0x003ADFFCu, "anonymous_namespace::UnitSetInvalidEternal(cmvm::CmContext*,int,bool)"},
    {"ev::UnitSetInvalidUseDoping", 0x003AE744u, "anonymous_namespace::UnitSetInvalidUseDoping(cmvm::CmContext*,int,bool)"},
    {"ev::UnitSetInvalidUseClassChange", 0x003AEF70u, "anonymous_namespace::UnitSetInvalidUseClassChange(cmvm::CmContext*,int,bool)"},
    {"ev::UnitShine", 0x003B10F8u, "anonymous_namespace::UnitShine(cmvm::CmContext*,int)"},
    {"ev::UnitSetDummyIcon", 0x003AB62Cu, "anonymous_namespace::UnitSetDummyIcon(cmvm::CmContext*,int)"},
    {"ev::AiSetSequence", 0x003A8934u, "anonymous_namespace::AiSetSequence(cmvm::CmContext*,int,int,const char*,const char*)"},
    {"ev::AiTstFlag", 0x003B0C44u, "anonymous_namespace::AiTstFlag(cmvm::CmContext*,int,int)"},
    {"ev::AiSetFlag", 0x003B0BFCu, "anonymous_namespace::AiSetFlag(cmvm::CmContext*,int,int)"},
    {"ev::AiClrFlag", 0x003B0B70u, "anonymous_namespace::AiClrFlag(cmvm::CmContext*,int,int)"},
    {"ev::AiSetBattleRate", 0x003A9C4Cu, "anonymous_namespace::AiSetBattleRate(cmvm::CmContext*,int,int)"},
    {"ev::AiSetHealRate", 0x003A88ACu, "anonymous_namespace::AiSetHealRate(cmvm::CmContext*,int,int,int)"},
    {"ev::AiGetHealRateA", 0x003A917Cu, "anonymous_namespace::AiGetHealRateA(cmvm::CmContext*,int)"},
    {"ev::AiGetHealRateB", 0x003A91C0u, "anonymous_namespace::AiGetHealRateB(cmvm::CmContext*,int)"},
    {"ev::AiSetActive", 0x003A776Cu, "anonymous_namespace::AiSetActive(cmvm::CmContext*,int,int)"},
    {"ev::AiGetActive", 0x003A7728u, "anonymous_namespace::AiGetActive(cmvm::CmContext*,int)"},
    {"ev::AiGetBand", 0x003B0BB8u, "anonymous_namespace::AiGetBand(cmvm::CmContext*,int)"},
    {"ev::AiSetMoveLimit", 0x003A9204u, "anonymous_namespace::AiSetMoveLimit(cmvm::CmContext*,int,int,int,int,int,int)"},
    {"ev::AiGetDisposX", 0x003A7E98u, "anonymous_namespace::AiGetDisposX(cmvm::CmContext*,int)"},
    {"ev::AiGetDisposY", 0x003A7EDCu, "anonymous_namespace::AiGetDisposY(cmvm::CmContext*,int)"},
    {"ev::AiSetDisposPosition", 0x003AC77Cu, "anonymous_namespace::AiSetDisposPosition(cmvm::CmContext*,int,int,int)"},
    {"ev::AiGetPriority", 0x003A8868u, "anonymous_namespace::AiGetPriority(cmvm::CmContext*,int)"},
    {"ev::AiSetPriority", 0x003A88F4u, "anonymous_namespace::AiSetPriority(cmvm::CmContext*,int,int)"},
    {"ev::TransporterItemIsExist", 0x003AE2F0u, "anonymous_namespace::TransporterItemIsExist(cmvm::CmContext*,const char*)"},
    {"ev::TransporterItemPutOff", 0x003ADF04u, "anonymous_namespace::TransporterItemPutOff(cmvm::CmContext*,const char*)"},
    {"ev::TransporterItemSetInvalidRefine", 0x001A6EF8u, "anonymous_namespace::TransporterItemSetInvalidRefine(cmvm::CmContext*,bool)"},
    {"ev::TerrainAttributeSetTID", 0x003AE1B0u, "anonymous_namespace::TerrainAttributeSetTID(cmvm::CmContext*,int,int,const char*)"},
    {"ev::TerrainAttributeIsTID", 0x003ADE7Cu, "anonymous_namespace::TerrainAttributeIsTID(cmvm::CmContext*,int,int,const char*)"},
    {"ev::TerrainAttributeIsTIDWithEdge", 0x003AF020u, "anonymous_namespace::TerrainAttributeIsTIDWithEdge(cmvm::CmContext*,int,int,const char*)"},
    {"ev::TerrainAttributeIsFlag", 0x003AE12Cu, "anonymous_namespace::TerrainAttributeIsFlag(cmvm::CmContext*,int,int,int)"},
    {"ev::TerrainAttributeRemoveObstacle", 0x003AF0A0u, "anonymous_namespace::TerrainAttributeRemoveObstacle(cmvm::CmContext*)"},
    {"ev::TerrainAttributeUpdatePosition", 0x003AF16Cu, "anonymous_namespace::TerrainAttributeUpdatePosition(cmvm::CmContext*,int,int)"},
    {"ev::TerrainAttributeUpdateArea", 0x003AEDFCu, "anonymous_namespace::TerrainAttributeUpdateArea(cmvm::CmContext*,int,int,int,int)"},
    {"ev::TrickGetForce", 0x003A8BE0u, "anonymous_namespace::TrickGetForce(cmvm::CmContext*)"},
    {"ev::TrickSetForce", 0x003A8C70u, "anonymous_namespace::TrickSetForce(cmvm::CmContext*,int)"},
    {"ev::TrickSet", 0x003B093Cu, "anonymous_namespace::TrickSet(cmvm::CmContext*,int,int,int,int,int)"},
    {"ev::TrickStringSet", 0x003A95DCu, "anonymous_namespace::TrickStringSet(cmvm::CmContext*,const char*,int,int,int)"},
    {"ev::TrickTst", 0x003B0A44u, "anonymous_namespace::TrickTst(cmvm::CmContext*,int,int,int,int)"},
    {"ev::TrickTryTst", 0x003A7BF4u, "anonymous_namespace::TrickTryTst(cmvm::CmContext*,int,int,int,int)"},
    {"ev::TrickGetHp", 0x003A724Cu, "anonymous_namespace::TrickGetHp(cmvm::CmContext*,int,int,int)"},
    {"ev::TrickSetHp", 0x003A72C8u, "anonymous_namespace::TrickSetHp(cmvm::CmContext*,int,int,int,int)"},
    {"ev::TrickGetMaxHp", 0x003A8BF4u, "anonymous_namespace::TrickGetMaxHp(cmvm::CmContext*,int,int,int)"},
    {"ev::TrickGetDragonAccessX", 0x003ADF5Cu, "anonymous_namespace::TrickGetDragonAccessX(cmvm::CmContext*)"},
    {"ev::TrickGetDragonAccessY", 0x003ADF70u, "anonymous_namespace::TrickGetDragonAccessY(cmvm::CmContext*)"},
    {"ev::TrickSetDragonFocus", 0x003AD024u, "anonymous_namespace::TrickSetDragonFocus(cmvm::CmContext*,int,int)"},
    {"ev::GimmickMedicine", 0x003AC8D4u, "anonymous_namespace::GimmickMedicine(cmvm::CmContext*,int,int)"},
    {"ev::GimmickMedicineString", 0x003ADE00u, "anonymous_namespace::GimmickMedicineString(cmvm::CmContext*,const char*)"},
    {"ev::GimmickWindBlow", 0x003AA030u, "anonymous_namespace::GimmickWindBlow(cmvm::CmContext*,int,int,int,int,bool)"},
    {"ev::MindGetForce", 0x003A80FCu, "anonymous_namespace::MindGetForce(cmvm::CmContext*)"},
    {"ev::MindGetUnit", 0x003A7AC0u, "anonymous_namespace::MindGetUnit(cmvm::CmContext*)"},
    {"ev::MindGetX", 0x003B07D0u, "anonymous_namespace::MindGetX(cmvm::CmContext*)"},
    {"ev::MindGetY", 0x003B07E0u, "anonymous_namespace::MindGetY(cmvm::CmContext*)"},
    {"ev::MindGetMind", 0x003A7AB0u, "anonymous_namespace::MindGetMind(cmvm::CmContext*)"},
    {"ev::MindGetTargetUnit", 0x003ABA88u, "anonymous_namespace::MindGetTargetUnit(cmvm::CmContext*)"},
    {"ev::MindGetTradeUnit", 0x003AAFCCu, "anonymous_namespace::MindGetTradeUnit(cmvm::CmContext*)"},
    {"ev::RouteGet", 0x003B0874u, "anonymous_namespace::RouteGet(cmvm::CmContext*)"},
    {"ev::RouteSet", 0x003B0884u, "anonymous_namespace::RouteSet(cmvm::CmContext*,int)"},
    {"ev::RouteIsBought", 0x001AC9B0u, "anonymous_namespace::RouteIsBought(cmvm::CmContext*,int)"},
    {"ev::ContentsGetPackage", 0x001ACBE4u, "anonymous_namespace::ContentsGetPackage(void)"},
    {"ev::DifficultyGet", 0x003A8A70u, "anonymous_namespace::DifficultyGet(cmvm::CmContext*)"},
    {"ev::DifficultyIsCasual", 0x003AC324u, "anonymous_namespace::DifficultyIsCasual(cmvm::CmContext*)"},
    {"ev::DifficultyIsPhoenix", 0x003AC820u, "anonymous_namespace::DifficultyIsPhoenix(cmvm::CmContext*)"},
    {"ev::ScenarioRankGet", 0x003AA874u, "anonymous_namespace::ScenarioRankGet(cmvm::CmContext*)"},
    {"ev::TurnGet", 0x003B06B0u, "anonymous_namespace::TurnGet(cmvm::CmContext*)"},
    {"ev::ItemGain", 0x003B0768u, "anonymous_namespace::ItemGain(cmvm::CmContext*,int,const char*)"},
    {"ev::ItemGainNoSound", 0x003AA52Cu, "anonymous_namespace::ItemGainNoSound(cmvm::CmContext*,int,const char*)"},
    {"ev::ItemGainSilent", 0x003A94A4u, "anonymous_namespace::ItemGainSilent(cmvm::CmContext*,int,const char*)"},
    {"ev::ItemReplaceForYatonokami", 0x003AE888u, "anonymous_namespace::ItemReplaceForYatonokami(cmvm::CmContext*,const char*,const char*)"},
    {"ev::ItemGainMessageOnly", 0x003ACF6Cu, "anonymous_namespace::ItemGainMessageOnly(cmvm::CmContext*,const char*)"},
    {"ev::ItemGainMessageOnlyNoSound", 0x003AED48u, "anonymous_namespace::ItemGainMessageOnlyNoSound(cmvm::CmContext*,const char*)"},
    {"ev::ItemGetKind", 0x003A7A7Cu, "anonymous_namespace::ItemGetKind(cmvm::CmContext*,const char*)"},
    {"ev::ItemGetOrigin", 0x003A8AE4u, "anonymous_namespace::ItemGetOrigin(cmvm::CmContext*,const char*)"},
    {"ev::ItemGetRandom", 0x003A8B14u, "anonymous_namespace::ItemGetRandom(cmvm::CmContext*,int,int,int)"},
    {"ev::GoldGain", 0x003B0728u, "anonymous_namespace::GoldGain(cmvm::CmContext*,int,int)"},
    {"ev::GoldGain2", 0x003B0D70u, "anonymous_namespace::GoldGain2(cmvm::CmContext*,int,int,const char*)"},
    {"ev::GoldGainSilent", 0x0035EA64u, "anonymous_namespace::GoldGainSilent(cmvm::CmContext*,int,int)"},
    {"ev::GoldGet", 0x003B0660u, "anonymous_namespace::GoldGet(cmvm::CmContext*)"},
    {"ev::AccessoryGain", 0x003A874Cu, "anonymous_namespace::AccessoryGain(cmvm::CmContext*,const char*)"},
    {"ev::AccessoryGainSilent", 0x003AC744u, "anonymous_namespace::AccessoryGainSilent(cmvm::CmContext*,const char*)"},
    {"ev::CameraSetPosition", 0x003AB714u, "anonymous_namespace::CameraSetPosition(cmvm::CmContext*,int,int)"},
    {"ev::CameraSetPositionByObject", 0x003AEB2Cu, "anonymous_namespace::CameraSetPositionByObject(cmvm::CmContext*,const char*)"},
    {"ev::CameraSetDistance", 0x003AB6E0u, "anonymous_namespace::CameraSetDistance(cmvm::CmContext*,int)"},
    {"ev::CameraSetDistanceFromConfig", 0x003AEE38u, "anonymous_namespace::CameraSetDistanceFromConfig(cmvm::CmContext*)"},
    {"ev::CameraSetDistanceFromNear", 0x003AEAF0u, "anonymous_namespace::CameraSetDistanceFromNear(cmvm::CmContext*)"},
    {"ev::CameraSetDistanceFromMiddle", 0x003AEE58u, "anonymous_namespace::CameraSetDistanceFromMiddle(cmvm::CmContext*)"},
    {"ev::CameraSetDistanceFromFar", 0x003AE7F4u, "anonymous_namespace::CameraSetDistanceFromFar(cmvm::CmContext*)"},
    {"ev::CameraSetAngle", 0x003A92A4u, "anonymous_namespace::CameraSetAngle(cmvm::CmContext*,int)"},
    {"ev::CameraSetAngleFromConfig", 0x003AE794u, "anonymous_namespace::CameraSetAngleFromConfig(cmvm::CmContext*)"},
    {"ev::CameraSetAngleFromNear", 0x003AE064u, "anonymous_namespace::CameraSetAngleFromNear(cmvm::CmContext*)"},
    {"ev::CameraSetAngleFromMiddle", 0x003AE7B8u, "anonymous_namespace::CameraSetAngleFromMiddle(cmvm::CmContext*)"},
    {"ev::CameraSetAngleFromFar", 0x003ADB6Cu, "anonymous_namespace::CameraSetAngleFromFar(cmvm::CmContext*)"},
    {"ev::CameraSetRoll", 0x003A89D8u, "anonymous_namespace::CameraSetRoll(cmvm::CmContext*,int)"},
    {"ev::CameraWait", 0x003A709Cu, "anonymous_namespace::CameraWait(cmvm::CmContext*)"},
    {"ev::CameraWaitDistance", 0x003AC288u, "anonymous_namespace::CameraWaitDistance(cmvm::CmContext*)"},
    {"ev::CameraWaitAngle", 0x003A9C8Cu, "anonymous_namespace::CameraWaitAngle(cmvm::CmContext*)"},
    {"ev::CameraInstant", 0x003E0CA8u, "anonymous_namespace::CameraInstant(cmvm::CmContext*)"},
    {"ev::CameraShake", 0x003A77BCu, "anonymous_namespace::CameraShake(cmvm::CmContext*,unsigned int,int,int,unsigned int)"},
    {"ev::CameraShakeForCastle", 0x003AD6FCu, "anonymous_namespace::CameraShakeForCastle(cmvm::CmContext*,unsigned int,int,int,unsigned int)"},
    {"ev::CameraStartShake", 0x003DFE84u, "anonymous_namespace::CameraStartShake(cmvm::CmContext*,unsigned int,int)"},
    {"ev::CameraStopShake", 0x003E0DFCu, "anonymous_namespace::CameraStopShake(cmvm::CmContext*,int,unsigned int)"},
    {"ev::EffectPlay3D", 0x003A7FA4u, "anonymous_namespace::EffectPlay3D(cmvm::CmContext*,const char*,int,int)"},
    {"ev::EffectPlayEternal3D", 0x003AC838u, "anonymous_namespace::EffectPlayEternal3D(cmvm::CmContext*,const char*,int,int)"},
    {"ev::EffectPlayUnit", 0x003A9348u, "anonymous_namespace::EffectPlayUnit(cmvm::CmContext*,const char*,int)"},
    {"ev::EffectRotate", 0x003A80B4u, "anonymous_namespace::EffectRotate(cmvm::CmContext*,int,int)"},
    {"ev::EffectFadeOut", 0x003A8A80u, "anonymous_namespace::EffectFadeOut(cmvm::CmContext*,int,int)"},
    {"ev::EffectDelete", 0x003A7F78u, "anonymous_namespace::EffectDelete(cmvm::CmContext*,int)"},
    {"ev::EffectIsPreload", 0x003A9DD8u, "anonymous_namespace::EffectIsPreload(cmvm::CmContext*,int)"},
    {"ev::EffectIsPlaying", 0x003A9DB8u, "anonymous_namespace::EffectIsPlaying(cmvm::CmContext*)"},
    {"ev::EffectHideTrick", 0x003A9DB0u, "anonymous_namespace::EffectHideTrick(cmvm::CmContext*)"},
    {"ev::EffectShowTrick", 0x003A9E04u, "anonymous_namespace::EffectShowTrick(cmvm::CmContext*)"},
    {"ev::TelopPlay", 0x003B0E4Cu, "anonymous_namespace::TelopPlay(cmvm::CmContext*,const char*)"},
    {"ev::TelopPlayDirect", 0x003AA884u, "anonymous_namespace::TelopPlayDirect(cmvm::CmContext*,const char*)"},
    {"ev::TelopIsWait", 0x003A7B08u, "anonymous_namespace::TelopIsWait(cmvm::CmContext*)"},
    {"ev::TutorialIsEnable", 0x003AB12Cu, "anonymous_namespace::TutorialIsEnable(cmvm::CmContext*)"},
    {"ev::TutorialShow", 0x003A8210u, "anonymous_namespace::TutorialShow(cmvm::CmContext*,const char*)"},
    {"ev::TutorialGetFlag", 0x0050C980u, "anonymous_namespace::TutorialGetFlag(cmvm::CmContext*,const char*)"},
    {"ev::TutorialSetFlag", 0x00202BB8u, "anonymous_namespace::TutorialSetFlag(cmvm::CmContext*,const char*)"},
    {"ev::TutorialSetFlagAll", 0x003AC3ACu, "anonymous_namespace::TutorialSetFlagAll(cmvm::CmContext*)"},
    {"ev::TutorialDialog", 0x003A976Cu, "anonymous_namespace::TutorialDialog(cmvm::CmContext*,const char*)"},
    {"ev::TutorialDialogMustShow", 0x003AE358u, "anonymous_namespace::TutorialDialogMustShow(cmvm::CmContext*,const char*)"},
    {"ev::TutorialIsAbleToAttack", 0x003AE3D0u, "anonymous_namespace::TutorialIsAbleToAttack(cmvm::CmContext*)"},
    {"ev::TutorialIsAbleToTalkForPickEvent", 0x003AF284u, "anonymous_namespace::TutorialIsAbleToTalkForPickEvent(cmvm::CmContext*)"},
    {"ev::MapSuspend", 0x003A7130u, "anonymous_namespace::MapSuspend(cmvm::CmContext*)"},
    {"ev::MapResume", 0x003B0E24u, "anonymous_namespace::MapResume(cmvm::CmContext*)"},
    {"ev::MapImageUpdate", 0x003A94E8u, "anonymous_namespace::MapImageUpdate(cmvm::CmContext*)"},
    {"ev::MoviePlayImpl", 0x003A8B80u, "anonymous_namespace::MoviePlayImpl(cmvm::CmContext*,const char*,bool)"},
    {"ev::MovieStop", 0x0041F108u, "anonymous_namespace::MovieStop(cmvm::CmContext*)"},
    {"ev::MovieIsExist", 0x003A81DCu, "anonymous_namespace::MovieIsExist(cmvm::CmContext*)"},
    {"ev::MovieIsPaused", 0x003A8B58u, "anonymous_namespace::MovieIsPaused(cmvm::CmContext*)"},
    {"ev::MovieIsSkipped", 0x0041F1A8u, "anonymous_namespace::MovieIsSkipped(cmvm::CmContext*)"},
    {"ev::MovieEnablePauseAtEnd", 0x0041F014u, "anonymous_namespace::MovieEnablePauseAtEnd(cmvm::CmContext*)"},
    {"ev::MovieDisablePauseAtEnd", 0x0041F0A0u, "anonymous_namespace::MovieDisablePauseAtEnd(cmvm::CmContext*)"},
    {"ev::Battle", 0x003AF3D8u, "anonymous_namespace::Battle(cmvm::CmContext*,int,int,int,int,const int*)"},
    {"ev::JoinGuest", 0x003B0DB4u, "anonymous_namespace::JoinGuest(cmvm::CmContext*,const char*,bool)"},
    {"ev::CardEntry", 0x003B0CC0u, "anonymous_namespace::CardEntry(cmvm::CmContext*,const char*)"},
    {"ev::CardIsExist", 0x003A7830u, "anonymous_namespace::CardIsExist(cmvm::CmContext*,const char*)"},
    {"ev::BGMPlay", 0x003AF674u, "anonymous_namespace::BGMPlay(cmvm::CmContext*,const char*,int)"},
    {"ev::BGMStop", 0x0041FB38u, "anonymous_namespace::BGMStop(cmvm::CmContext*,int)"},
    {"ev::RBGMPlay", 0x003B07F0u, "anonymous_namespace::RBGMPlay(cmvm::CmContext*,const char*,int)"},
    {"ev::RBGMStop", 0x003B084Cu, "anonymous_namespace::RBGMStop(cmvm::CmContext*,int)"},
    {"ev::RBGMEffect", 0x003A71A4u, "anonymous_namespace::RBGMEffect(cmvm::CmContext*,int)"},
    {"ev::BGMVolume", 0x003B0C90u, "anonymous_namespace::BGMVolume(cmvm::CmContext*,int,int)"},
    {"ev::EnableBGMCommandPG", 0x0041FAACu, "anonymous_namespace::EnableBGMCommandPG(cmvm::CmContext*)"},
    {"ev::DisableBGMCommandPG", 0x0041FB10u, "anonymous_namespace::DisableBGMCommandPG(cmvm::CmContext*)"},
    {"ev::BMapBGMChnageFlagOn", 0x003AC7C4u, "anonymous_namespace::BMapBGMChnageFlagOn(cmvm::CmContext*)"},
    {"ev::BMapBGMResume", 0x003A89D0u, "anonymous_namespace::BMapBGMResume(cmvm::CmContext*,int)"},
    {"ev::SEPlay", 0x003AF63Cu, "anonymous_namespace::SEPlay(cmvm::CmContext*,const char*)"},
    {"ev::SEPlay3D", 0x003B08A0u, "anonymous_namespace::SEPlay3D(cmvm::CmContext*,const char*,int,int)"},
    {"ev::LSEPlay", 0x003B0670u, "anonymous_namespace::LSEPlay(cmvm::CmContext*,const char*,int)"},
    {"ev::LSEStop", 0x00420344u, "anonymous_namespace::LSEStop(cmvm::CmContext*,const char*,int)"},
    {"ev::LSEVolume", 0x00420A48u, "anonymous_namespace::LSEVolume(cmvm::CmContext*,const char*,int,int)"},
    {"ev::Voice", 0x003AF3A0u, "anonymous_namespace::Voice(cmvm::CmContext*,const char*)"},
    {"ev::EnvSEOff", 0x003B06C8u, "anonymous_namespace::EnvSEOff(cmvm::CmContext*,int)"},
    {"ev::EnvSEOn", 0x003B04A4u, "anonymous_namespace::EnvSEOn(cmvm::CmContext*,int)"},
    {"ev::VoiceArchiveLoad", 0x0041FE2Cu, "anonymous_namespace::VoiceArchiveLoad(cmvm::CmContext*,const char*)"},
    {"ev::VoiceArchiveFree", 0x0041FD68u, "anonymous_namespace::VoiceArchiveFree(cmvm::CmContext*,const char*)"},
    {"ev::MiracleTelop", 0x003A81C0u, "anonymous_namespace::MiracleTelop(cmvm::CmContext*)"},
    {"ev::MiracleShoot", 0x003A8110u, "anonymous_namespace::MiracleShoot(cmvm::CmContext*,int,int,const char*)"},
    {"ev::MiracleShootXY", 0x003A9524u, "anonymous_namespace::MiracleShootXY(cmvm::CmContext*,int,int,int,int)"},
    {"ev::MiracleGetShootX", 0x003AAFDCu, "anonymous_namespace::MiracleGetShootX(cmvm::CmContext*,const char*)"},
    {"ev::MiracleGetShootY", 0x003AB024u, "anonymous_namespace::MiracleGetShootY(cmvm::CmContext*,const char*)"},
    {"ev::GMapMove", 0x003B06D0u, "anonymous_namespace::GMapMove(cmvm::CmContext*,const char*,const char*,unsigned int)"},
    {"ev::FieldObjectPlayState", 0x003AD84Cu, "anonymous_namespace::FieldObjectPlayState(cmvm::CmContext*,const char*,int)"},
    {"ev::FieldObjectSetState", 0x003AC89Cu, "anonymous_namespace::FieldObjectSetState(cmvm::CmContext*,const char*,int)"},
    {"ev::FieldObjectSetVisible", 0x003ADD10u, "anonymous_namespace::FieldObjectSetVisible(cmvm::CmContext*,const char*,bool)"},
    {"ev::FieldObjectSetEscape", 0x003AD8E8u, "anonymous_namespace::FieldObjectSetEscape(cmvm::CmContext*,const char*,bool)"},
    {"ev::FieldObjectCreate", 0x003AB7B0u, "anonymous_namespace::FieldObjectCreate(cmvm::CmContext*,const char*)"},
    {"ev::FieldObjectDelete", 0x003AB7D4u, "anonymous_namespace::FieldObjectDelete(cmvm::CmContext*,const char*)"},
    {"ev::FieldObjectMove", 0x003A9E8Cu, "anonymous_namespace::FieldObjectMove(cmvm::CmContext*,const char*,int,int,const char*)"},
    {"ev::FieldObjectMoveEx", 0x003AB7F4u, "anonymous_namespace::FieldObjectMoveEx(cmvm::CmContext*,const char*,int,int,int,const char*)"},
    {"ev::FieldObjectWarp", 0x0042E960u, "anonymous_namespace::FieldObjectWarp(cmvm::CmContext*,const char*,const char*)"},
    {"ev::FieldObjectFadeOut", 0x0042F594u, "anonymous_namespace::FieldObjectFadeOut(cmvm::CmContext*,const char*,int)"},
    {"ev::FieldObjectPlayAnime", 0x003AD7FCu, "anonymous_namespace::FieldObjectPlayAnime(cmvm::CmContext*,const char*,const char*)"},
    {"ev::FieldObjectPlayEffect", 0x003ADC28u, "anonymous_namespace::FieldObjectPlayEffect(cmvm::CmContext*,const char*,const char*,const char*)"},
    {"ev::UnitRescue", 0x003A7504u, "anonymous_namespace::UnitRescue(cmvm::CmContext*,int)"},
    {"ev::UnitRescueAll", 0x003A8FBCu, "anonymous_namespace::UnitRescueAll(cmvm::CmContext*)"},
    {"ev::LilithDie", 0x003B0E08u, "anonymous_namespace::LilithDie(cmvm::CmContext*)"},
    {"ev::EpithetUnlock", 0x003A8AB4u, "anonymous_namespace::EpithetUnlock(cmvm::CmContext*,int)"},
    {"ev::AnnaMessageSet", 0x003A9274u, "anonymous_namespace::AnnaMessageSet(cmvm::CmContext*,const char*)"},
    {"ev::AnnaMessageClr", 0x003A9260u, "anonymous_namespace::AnnaMessageClr(cmvm::CmContext*)"},
    {"ev::BandOpen", 0x00422A80u, "anonymous_namespace::BandOpen(cmvm::CmContext*)"},
    {"ev::BandClose", 0x00423CD0u, "anonymous_namespace::BandClose(cmvm::CmContext*)"},
    {"ev::CrossFade", 0x003B0CECu, "anonymous_namespace::CrossFade(cmvm::CmContext*,int)"},
    {"ev::ContentsGetFlag", 0x003A9D30u, "anonymous_namespace::ContentsGetFlag(cmvm::CmContext*,int)"},
    {"ev::ContentsSetFlag", 0x003A9D54u, "anonymous_namespace::ContentsSetFlag(cmvm::CmContext*,int)"},
    {"ev::ContentsClrFlag", 0x003A9D00u, "anonymous_namespace::ContentsClrFlag(cmvm::CmContext*,int)"},
    {"ev::ContentsGetIndex", 0x003AAF10u, "anonymous_namespace::ContentsGetIndex(cmvm::CmContext*)"},
    {"ev::ContentsGetElapse", 0x003AB75Cu, "anonymous_namespace::ContentsGetElapse(cmvm::CmContext*,int)"},
    {"ev::ContentsUpdateTime", 0x003AC2FCu, "anonymous_namespace::ContentsUpdateTime(cmvm::CmContext*,int)"},
    {"ev::ComebackCastle", 0x003A9330u, "anonymous_namespace::ComebackCastle(cmvm::CmContext*)"},
    {"ev::AmiiboUpdate", 0x003A7F20u, "anonymous_namespace::AmiiboUpdate(cmvm::CmContext*,int)"},
};
}
const CommandBinding* GetCommandBindings(){return kBindings;}
std::size_t GetCommandBindingCount(){return sizeof(kBindings)/sizeof(kBindings[0]);}
}
