#include "fates/event/event_triggers.hpp"
#include "fates/detail/event_runtime.hpp"
namespace event {
#define SIMPLE(Name) namespace Name { void Trigger(ProcInst* p){fates::decomp_detail::EventRuntimeCall("event." #Name ".Trigger",p);} bool Inspector(cmvm::CmFunction* f,const Arg* a){return fates::decomp_detail::EventRuntimeValue<bool>("event." #Name ".Inspector",f,a);} }
SIMPLE(BattleInfo) SIMPLE(MapSetting) SIMPLE(TurnTerrain) SIMPLE(UnitCommand) SIMPLE(MapSettingResume) SIMPLE(MapSettingEncount) SIMPLE(AfterSortie) SIMPLE(Turn) SIMPLE(TurnAfter) SIMPLE(Reinforce)
#undef SIMPLE
namespace BattleTalk {cmvm::CmFunction* GetFunction(const Arg* a){return fates::decomp_detail::EventRuntimeValue<cmvm::CmFunction*>("event.BattleTalk.GetFunction",a);} bool Check(const Unit* a,const Unit* b){return fates::decomp_detail::EventRuntimeValue<bool>("event.BattleTalk.Check",a,b);} void Trigger(ProcInst* p,const Unit* a,const Unit* b){fates::decomp_detail::EventRuntimeCall("event.BattleTalk.Trigger",p,a,b);}}
namespace InstantDie {void Trigger(ProcInst* p,const Unit* u){fates::decomp_detail::EventRuntimeCall("event.InstantDie.Trigger",p,u);} bool Inspector(cmvm::CmFunction* f,const Arg* a){return fates::decomp_detail::EventRuntimeValue<bool>("event.InstantDie.Inspector",f,a);}}
namespace InstantBattle {cmvm::CmFunction* GetFunction(const Arg* a){return fates::decomp_detail::EventRuntimeValue<cmvm::CmFunction*>("event.InstantBattle.GetFunction",a);} void Trigger(ProcInst* p,const Unit* a,const Unit* b){fates::decomp_detail::EventRuntimeCall("event.InstantBattle.Trigger",p,a,b);}}
namespace Die {cmvm::CmFunction* GetFunction(Function::Type t,const Arg* a){return fates::decomp_detail::EventRuntimeValue<cmvm::CmFunction*>("event.Die.GetFunction",t,a);} bool Check(const Unit* a,const Unit* b){return fates::decomp_detail::EventRuntimeValue<bool>("event.Die.Check",a,b);} void Trigger(ProcInst* p,const Unit* a,const Unit* b){fates::decomp_detail::EventRuntimeCall("event.Die.Trigger",p,a,b);}}
namespace Area {void Trigger(ProcInst* p,int x,int y){fates::decomp_detail::EventRuntimeCall("event.Area.Trigger",p,x,y);} bool Inspector(cmvm::CmFunction* f,const Arg* a){return fates::decomp_detail::EventRuntimeValue<bool>("event.Area.Inspector",f,a);}}
namespace Pick {void Trigger(ProcInst* p,const Unit* u){fates::decomp_detail::EventRuntimeCall("event.Pick.Trigger",p,u);} bool Inspector(cmvm::CmFunction* f,const Arg* a){return fates::decomp_detail::EventRuntimeValue<bool>("event.Pick.Inspector",f,a);}}
namespace Poke {bool Check(int x,int y,map::trick::Type t){return fates::decomp_detail::EventRuntimeValue<bool>("event.Poke.Check",x,y,t);} void Trigger(ProcInst* p,int x,int y,map::trick::Type t){fates::decomp_detail::EventRuntimeCall("event.Poke.Trigger",p,x,y,t);} bool Inspector(cmvm::CmFunction* f,const Arg* a){return fates::decomp_detail::EventRuntimeValue<bool>("event.Poke.Inspector",f,a);}}
namespace Talk {bool Check(const Unit* a,const Unit* b){return fates::decomp_detail::EventRuntimeValue<bool>("event.Talk.Check",a,b);} void Trigger(ProcInst* p,const Unit* a,const Unit* b){fates::decomp_detail::EventRuntimeCall("event.Talk.Trigger",p,a,b);} bool Inspector(cmvm::CmFunction* f,const Arg* a){return fates::decomp_detail::EventRuntimeValue<bool>("event.Talk.Inspector",f,a);}}
namespace Escape {void Trigger(ProcInst* p,const Unit* u){fates::decomp_detail::EventRuntimeCall("event.Escape.Trigger",p,u);} bool Inspector(cmvm::CmFunction* f,const Arg* a){return fates::decomp_detail::EventRuntimeValue<bool>("event.Escape.Inspector",f,a);}}
namespace Ending{void Trigger(ProcInst* p){fates::decomp_detail::EventRuntimeCall("event.Ending.Trigger",p);}} namespace MapFree{void Trigger(ProcInst* p){fates::decomp_detail::EventRuntimeCall("event.MapFree.Trigger",p);}} namespace MapLoad{void Trigger(ProcInst* p){fates::decomp_detail::EventRuntimeCall("event.MapLoad.Trigger",p);}} namespace Opening{void Trigger(ProcInst* p){fates::decomp_detail::EventRuntimeCall("event.Opening.Trigger",p);}} namespace Complete{void Trigger(ProcInst* p){fates::decomp_detail::EventRuntimeCall("event.Complete.Trigger",p);}} namespace GameOver{void Trigger(ProcInst* p){fates::decomp_detail::EventRuntimeCall("event.GameOver.Trigger",p);}}
}
