#pragma once
#include <cstdint>
#include "fates/game/gameplay_types.hpp"
#include "fates/game/item_kinds.hpp"
#include "fates/game/unit_item.hpp"

class Unit {
public:
    struct ExpMode { enum class Type : int {}; };

    // Lifecycle, construction, transfer and serialization.
    void AIActivate(bool a0);
    bool CreateImpl(const Person* a0, const Job* a1, int a2, Random* a3);
    void Initialize(int a0);
    void CreateEdit(const unit::Edit* a0);
    void UpdateEdit();
    void ClassChange(const Job* a0, int a1);
    map::Actor* CreateActor();
    void CreateClone(Unit* a0);
    void CreateForCastleJoin(const Person* a0);
    void CreateImpl2(bool a0, bool a1);
    void Deserialize(Stream* a0);
    void DetachClone();
    void UpdateActor();
    void UpdateClone();
    void TransferForSortie(Force::Type a0, bool a1);
    void TransferImpl(Force::Type a0, bool a1, bool a2);
    void CopyForBackup(const Unit* a0);
    void ResetEndOfMap(bool a0, bool a1);
    void UpdateCloneHP();
    void CopyForLevelUp(const Unit* a0);
    void CopyForRestore(Unit* a0, bool a1, bool a2);
    void SetPlayerBelong();
    void UpdateCloneItem();
    void UpdateHairColor();
    void CreateFromDispos(const void* a0, int a1);
    void CreateFromPacket(const game::packet::Unit* a0);
    void AIActivate_CauseAttacked(bool a0);
    void CreateFromExtendedPacket(const game::packet::ExtendedUnit* a0, bool a1);
    void Copy(const Unit* a0);
    void Clear();
    void Create(const Person* a0, const Job* a1, int a2, Random* a3);
    void LevelUp();
    void DoubleOn(Unit* a0);
    void Handover(bool a0);
    void Inherit2();
    void Transfer(Force::Type a0, bool a1);
    void DoubleOff();
    void Reinstate(const void* a0);
    void SetDispos(const void* a0);
    Unit();
    ~Unit();
    Unit& operator=(const Unit& a0);
    void CreateFromClerk(const Person* a0, const Job* a1);

    // Reliance, family and relationship state.
    void RelianceUp(Unit* a0);
    void SetReliance(const Reliance* a0, int a1);
    void CreateReliance(const unsigned char* a0);
    void DeleteReliance();
    void SetRelianceLevel(Unit* a0, int a1);
    void AddChapterReliance(const Unit* a0, int a1);
    static void AddChapterReliance(Unit* a0, Unit* a1, int a2);
    void CreateChapterReliance(const unsigned char* a0);
    void DeleteChapterReliance();
    static bool ChapterRelianceRankSortComp(unsigned int a0, unsigned int a1, void* a2);
    bool IsReliance(const Unit* a0) const;
    std::uint8_t GetReliance(const Reliance* a0) const;
    bool IsRelianceUp(const Unit* a0) const;
    std::uint32_t GetMarrigePid() const;
    bool CanDoubleTrade(const Unit* a0) const;
    int GetDualSupport(BattleCapability::Type a0, int a1) const;
    bool IsRelianceTalk(const Unit* a0, int a1) const;
    const Person* GetMarrigePerson() const;
    int GetRelianceLevel(const Unit* a0) const;
    bool IsFamilyUncleAunt(const Unit* a0) const;
    bool IsRelianceInvalid() const;
    std::uint8_t GetChapterReliance(const Unit* a0) const;
    Unit* GetFamilyChild(const Unit* a0) const;
    Unit* GetFamilyChildImpl(const Unit* a0) const;
    int GetRelianceMaxLevel(const Unit* a0) const;
    bool IsFamilyParentChild(const Unit* a0) const;
    int GetRelianceScoreImpl(bool* a0, int* a1, int* a2, int* a3, const Unit* a4) const;
    bool IsFamilyBrotherSister(const Unit* a0) const;
    int GetChapterRelianceRank(const Unit* a0) const;
    int GetRelianceScoreForDual(const Unit* a0) const;
    int GetRelianceScoreForUnitStatus(const Unit* a0) const;
    bool IsSortieForUnitStatusReliance() const;
    bool IsRelianceInvalidForClassChange() const;
    bool IsFamily(const Unit* a0) const;
    bool IsMarrige() const;
    bool IsRomance(const Unit* a0) const;

    // Inventory, equipment and skill handling.
    void ItemCloseUp();
    void ItemTakeOff(int a0);
    void AddWeaponExp(ItemKind::Type a0, int a1);
    bool AddEquipSkill(short a0);
    void ItemPutOffAll();
    void WeaponBuildup();
    unit::Item* GetItemEquipped();
    void InheritEquipSkill(const short* a0);
    void LearnFromDictionary(short a0);
    void DeleteEquipSkillFromIndex(int a0, bool a1);
    void DeleteEquipSkillUnknownAndEnemyOnlyWithPool();
    int ItemAdd(const unit::Item* a0);
    bool ItemUse(const unit::Item* a0);
    void ItemMove(int a0, int a1);
    bool SetDisposItem(const void* a0);
    bool ItemEquip(int a0);
    void ItemPutOff(int a0, bool a1);
    bool CanItemUse(const unit::Item* a0) const;
    bool CanItemEquip(const unit::Item* a0, bool a1, bool a2) const;
    int GetWeaponExp(ItemKind::Type a0) const;
    bool IsEquipSkill(short a0) const;
    bool CanCannonItem(const unit::Item* a0, bool a1) const;
    int GetContinuous(const unit::Item* a0) const;
    int GetHasItemNum() const;
    bool HasCheerSkill() const;
    bool HasDanceSkill() const;
    const unit::Item* GetItemEquipped() const;
    bool IsItemCanCannon(bool a0) const;
    int GetItemHealPower(const unit::Item* a0) const;
    int GetItemIndexHold() const;
    int GetWeaponExpLimit(ItemKind::Type a0) const;
    bool HasCheerSkillMove() const;
    bool IsItemEnhanceHave(const unit::Item* a0, bool a1) const;
    std::uint16_t GetIndividualSkill() const;
    int GetHasEquipSkillNum() const;
    int GetItemIndexKeyDoor() const;
    bool IsItemRangeCanEquip(int a0) const;
    bool IsItemSkillCanEquip(unsigned long long a0) const;
    int GetItemIndexEquipped() const;
    int GetInterferenceRodHit(const unit::Item* a0) const;
    bool IsLearnFromDictionary(short a0) const;
    int CaclulateFirstWeaponExp(ItemKind::Data* a0) const;
    int GetInterferenceRodAvoid(const unit::Item* a0) const;
    int GetItemMaxRangeCanEquip(bool a0) const;
    int GetWeaponExpForJobIntro(ItemKind::Type a0) const;
    bool HasCheerSkillCapability() const;
    int GetEquipSkillProbability(short a0, bool a1) const;
    int GetItemIndexKeyTreasureBox() const;
    const ::Item* GetBasicItemCanEquipForArena() const;

    // Combat statistics, capability and gameplay queries.
    map::Actor* ReplaceActor(map::Actor* a0);
    void SortEquipSkill();
    void SetCapabilityJust(int a0, int a1);
    void UpdateLimitOffset();
    int CollectiveLevelUpCapability(int a0, bool a1);
    const Job* GetCollectiveLevelUpClassChangeJob();
    bool CanKeyDoor() const;
    const char* GetDeadBGM() const;
    int GetDefImpl(const unit::Item* a0, bool a1, bool a2, unit::detail::EnhanceDefinition::Type a3) const;
    int GetMHPImpl(bool a0, bool a1, unit::detail::EnhanceDefinition::Type a2) const;
    int GetPowImpl(const unit::Item* a0, bool a1, bool a2, unit::detail::EnhanceDefinition::Type a3) const;
    int GetStrImpl(const unit::Item* a0, bool a1, bool a2, unit::detail::EnhanceDefinition::Type a3) const;
    bool IsCostFree() const;
    bool CanCaptured() const;
    bool CanCheerUse(const Unit* a0, int a1) const;
    bool CanDanceUse(const Unit* a0) const;
    bool CanDoubleOn(const Unit* a0) const;
    std::uint16_t GetCategory() const;
    int GetCritical(int a0) const;
    int GetCritical(const unit::Item* a0) const;
    int GetExpDance(Unit::ExpMode::Type a0, const Unit* a1) const;
    int GetLowLevel() const;
    int GetLuckImpl(const unit::Item* a0, bool a1, bool a2, unit::detail::EnhanceDefinition::Type a3) const;
    int GetMdefImpl(const unit::Item* a0, bool a1, bool a2, unit::detail::EnhanceDefinition::Type a3) const;
    int GetTechImpl(const unit::Item* a0, bool a1, bool a2, unit::detail::EnhanceDefinition::Type a3) const;
    bool IsInvisible() const;
    int ExpNormalize(int a0) const;
    int GetDualExpDestroy(Unit::ExpMode::Type a0, const Unit* a1) const;
    int GetExpDamage(Unit::ExpMode::Type a0, const Unit* a1) const;
    int GetMovePower(bool a0, unit::detail::EnhanceDefinition::Type a1) const;
    int GetQuickImpl(const unit::Item* a0, bool a1, bool a2, unit::detail::EnhanceDefinition::Type a3) const;
    int GetShowLevel() const;
    bool IsDontAttack(const Unit* a0, bool a1) const;
    bool CanDragonVein() const;
    int GetCannonArea() const;
    int GetExpDestroy(Unit::ExpMode::Type a0, const Unit* a1, bool a2) const;
    int GetLimitLevel() const;
    int GetCannonRangeI() const;
    int GetCannonRangeO() const;
    int GetEntrustForAI() const;
    int GetRodHealPower(const unit::Item* a0, const Unit* a1) const;
    bool IsSpecialBattle() const;
    int GetDualExpDamage(Unit::ExpMode::Type a0, const Unit* a1) const;
    void ToExtendedPacket(game::packet::ExtendedUnit* a0, bool a1) const;
    bool CanKeyTreasureBox() const;
    int GetCapabilityImpl(int a0, const unit::Item* a1, bool a2, bool a3, unit::detail::EnhanceDefinition::Type a4) const;
    bool IsUniqueWithClone() const;
    int GetDoubleMovePower(const Unit* a0) const;
    int GetEntrustForCount() const;
    Force::Type GetForceAbsentType() const;
    int GetUnderContinuous(const unit::Item* a0) const;
    bool IsDetailBattleMust() const;
    int GetAttackForTerrain(int a0) const;
    int GetCapabilityRating() const;
    int GetDoubleCapability(int a0, const Unit* a1) const;
    bool IsDeadProductionHigh() const;
    int GetDeadProductionLevel() const;
    bool IsDetailBattleNotAllow() const;
    int GetLevelForCalculateExp() const;
    void CaclulateAutoGrowCapability(Capability* a0, int a1) const;
    int GetLearnFromDictionaryPrice(short a0) const;
    int GetNoWeaknessCapabilityRating() const;
    int GetHit(int a0, bool a1) const;
    int GetHit(const unit::Item* a0, bool a1) const;
    int GetGrow(int a0) const;
    const wchar_t* GetName() const;
    Unit* GetNext(unsigned int a0) const;
    Unit* GetPrev(unsigned int a0) const;
    bool IsWrong() const;
    int GetAvoid(int a0) const;
    int GetAvoid(const unit::Item* a0) const;
    int GetLimit(int a0) const;
    bool IsFemale() const;
    bool IsLeader() const;
    bool IsUnique() const;
    void ToPacket(game::packet::Unit* a0, bool a1) const;
    bool CanCannon() const;
    int GetAttackForTerrain(const unit::Item* a0) const;
    int GetAttack(const unit::Item* a0, bool a1) const;
    int GetAttack(int a0, bool a1) const;
    int GetExpRod(Unit::ExpMode::Type a0, const unit::Item* a1, const Unit* a2) const;
    int GetRangeI(const unit::Item* a0) const;
    int GetRangeO(const unit::Item* a0) const;
    int GetSecure(const unit::Item* a0) const;
    bool IsNotIcon() const;
    void Serialize(Stream* a0) const;
    const wchar_t* GetHelp() const;

};
