#pragma once
#include <cstddef>
#include <cstdint>

namespace fates::services {

using ServiceWord = std::intptr_t;

enum class ServiceOwner : std::uint8_t { Field, State, Message, Transporter, VisualMedia, Audio, MapHandle, Other };

struct ServiceSpec { const char* retail_symbol; std::uint32_t retail_address; const char* retail_signature; ServiceOwner owner; };

struct ServiceRuntime { using InvokeFn = ServiceWord (*)(void* user, const ServiceSpec& spec, const ServiceWord* args, std::size_t argc); void* user=nullptr; InvokeFn invoke=nullptr; };

const ServiceSpec* GetServiceSpecs();
std::size_t GetServiceSpecCount();
const ServiceSpec* FindServiceSpec(std::uint32_t retail_address);
ServiceWord InvokeService(ServiceRuntime&, std::uint32_t retail_address, const ServiceWord* args, std::size_t argc);

// Layout-independent retail policies proven in this pass.
std::uint8_t DecodeGameMode(std::uint32_t flags);
std::uint32_t EncodeGameMode(std::uint32_t flags, std::uint8_t mode);
bool GameSkipIsWait(std::uint8_t state, std::uint32_t flags);
std::uint32_t GameSkipRequestEscape(std::uint8_t state, std::uint32_t flags);
bool MapLoadedByte(std::uint8_t loaded);
bool FieldObjectVisible(std::uint8_t flags);
bool FieldObjectAccessPlaying(std::int8_t access_state);
bool FadePairIsBlackOut(bool first_exists, std::uint8_t first_alpha, bool second_exists, std::uint8_t second_alpha);
bool FadeSlotIsActiveFadeIn(bool exists, bool started, bool ending);
bool DeliveryMessageExists(std::int16_t first_word);

// One source-facing wrapper per meaningful retail service function. Exact retail signatures remain in ServiceSpec/evidence.
ServiceWord Fade__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__Tick(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__Finalize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__SetSound(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__Reset(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__ChangeFree(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__ChangeLoad(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__ChangeTime(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__FindObject_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__FindObject_3(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__RemoveData(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetGeometry(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__SetCallback(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__SetKeepTime(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__SetLevelPos(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__UpdateRange(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__ChangeResume(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__DeleteObject_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetCollision(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__UpdateDispos(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__ChangeSuspend(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetObjectList(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetEffectColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__CalcGeometryHit(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetFaceLowerColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetFaceUpperColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetGeometryHeight(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetUnitLowerColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetUnitUpperColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Draw(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Free(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Load(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Tick(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Resume(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Update(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetArea(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__SetTime(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Finalize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__IsLoaded(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__IsLoaded_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__EntryData(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__GetCamera(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__UpdateAll(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameHandle__Release(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameHandle__GameHandle_3(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameHandle__operator(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__PlayAccess(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__SkipAccess(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__UpdateColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__SetTransform(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__UpdateAccess(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__UpdateDispos(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__UpdateEffect(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__SetTranslate(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__UpdateTransform(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__Free(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__Load(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__Update(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__FadeOut(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__SetPose(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__SetAlpha(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__SetColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__SetLevel(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__FieldObject(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__FieldObject_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__ResetLocal(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__ClrNotExist(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__FlagManager(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__FlagManager_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__Persistent(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__WindowOpen(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__CreateFatal(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__WindowClose(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__CreateSystem(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__DarknessStop(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__CreateKeyWait(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__CreateWarning(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__DarknessStart(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__RecoverParentMenu(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__CreateKeyTouchWaitLower(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__Tick(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__Setup(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__Create(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__IsWait(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__SEOpen(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__SEClose(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__DrawFont(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__GameMessage(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__GameMessage_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameMessage__GameMessage_3(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__GetExistNum(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__ClearInvalidRefine(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__anonymous_namespace__GetPrice(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__Sub(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__Data__Data(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__Reset(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__Finalize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__GetIndex(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Transporter__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__ReleaseBackup(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__SetSequenceForDesc(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__ClearDownloadContents(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__Reset(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__SetMode(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__Finalize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__GameUserData(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__Destruct(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ContentsLocal__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ContentsLocal__Reset(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldWorld__FindObject_4(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord DeliveryMessage__Commit(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord VariableManager__ResetLocal(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord VariableManager__ClrNotExist(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord VariableManager__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord VariableManager__Reset(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord VariableManager__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord VariableManager__VariableManager(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord VariableManager__VariableManager_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameSkipSequenceHelper__WaitSkip(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Map__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Map__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Map__Finalize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Map__IsLoaded(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__GetGoalColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__IsBlackOutAll(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__IsActiveFadeIn(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__BlackIn(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__WhiteIn(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__BlackOut(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__GetAlpha(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__GetColor(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__WaitBind(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Fade__WhiteOut(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__SetSkipped(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__GetFilePath(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__GetFileRoute(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__IsPauseAtEnd(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__EnablePauseAtEnd(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__GetNowVideoFrame(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__CreateOpeningBind(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__DisablePauseAtEnd(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__Destroy(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Movie__IsSkipped(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SetVolumeSE(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SEIsPrepared(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SetVolumeBGM(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__StopAllVoice(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLCSoundUpdate(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SEPlayPrepared(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SetVolumeSysSE(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SetVolumeVoice(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__BGMPlayPosition(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SetVoiceCallback(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__CallVoiceCallback(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DisableBGMCommand(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__LoadGroupCommonAsync(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__OnPlugHeadphoneChange(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__IsDLCSound(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__GetDLCIndex(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__VoiceArchiveFree(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__VoiceArchiveLoad(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__StreamArchiveFree(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__StreamArchiveLoad(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__GetDelay(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__DLC__IsDLCUnit(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__MEPlay(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SEStop(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__LSEStop(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__LSEStop_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__StopAll(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__BGMPause(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SEPlay2D(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SEPlay2D_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SEPlay3D(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__BGMResume(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__Construct(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__EnvVolume(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__GetCutOff(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__IsVoicing(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__LSEVolume(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__SEPrepare(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound__StopAllSE(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__IsRouteOrigin(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord DeliveryMessage__Deserialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__Initialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__GetRentCount(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__SetListenerMtx(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__RentSoundActor3D(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__ReturnSoundActor3D(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__FadeoutMasterVolume(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__CalcDefaultListenerMatrix(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Sound3D__Sound3D(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameSkip__Tick(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameSkip__Escape(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameSkip__IsWait(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameSkip__Render(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameSkip__GameSkip(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameSkip__GameSkip_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ProcMovie__ThreadStart(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ProcMovie__Tick(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ProcMovie__ThreadEnd(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ProcMovie__ProcMovie(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ProcMovie__ProcMovie_3(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameHandle__operator_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameHandle__operator_3(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__GetChangeMap(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__GetLocatorPos(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__IsPlayingAccess(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__GetRange(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__IsInside(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__GetCenter(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__Get(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagManager__Get_2(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__IsCastleTime(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__GetChapterName(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__IsChapterRecord(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__GetChapterPrefix(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__GetWinRuleMessage(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__GetMode(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord GameUserData__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord ContentsLocal__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord DeliveryMessage__GetMessage(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord DeliveryMessage__IsExist(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord DeliveryMessage__IsChanged(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord DeliveryMessage__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FlagNameManager__GetIndex(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord Map__Serialize(ServiceRuntime&, const ServiceWord* args, std::size_t argc);
ServiceWord FieldObject__IsVisible(ServiceRuntime&, const ServiceWord* args, std::size_t argc);

} // namespace fates::services
