#include "fates/graphics/transition_camera.hpp"
#include "fates/detail/specialized_camera_runtime.hpp"
TransitionCamera::TransitionCamera(float d):duration_(d){fates::decomp_detail::TransitionInitialize(*this,d);} TransitionCamera::~TransitionCamera(){fates::decomp_detail::TransitionDispose(*this);} void TransitionCamera::CreateZoomInCurve(){fates::decomp_detail::TransitionCreateZoomCurve(*this);} void TransitionCamera::CreateEncountCurve(){fates::decomp_detail::TransitionCreateEncounterCurve(*this);} void TransitionCamera::CreateCommeBackCurve(){fates::decomp_detail::TransitionCreateComebackCurve(*this);} void TransitionCamera::Tick(){fates::decomp_detail::TransitionTick(*this);} int TransitionCamera::GetModeType()const{return 0;} bool TransitionCamera::CanChangeMode()const{return false;} bool TransitionCamera::CanLookAround()const{return false;} bool TransitionCamera::IsChangeBattle()const{return fates::decomp_detail::TransitionChangedBattle(*this);} float TransitionCamera::GetTime()const{return fates::decomp_detail::TransitionTime(*this);} bool TransitionCamera::IsHitPos()const{return true;} bool TransitionCamera::IsHitArea()const{return true;} bool TransitionCamera::IsHitFovy()const{return false;}
ZoomInCamera::ZoomInCamera():TransitionCamera(){fates::decomp_detail::ZoomInInitialize(*this);} ZoomInCamera::~ZoomInCamera()=default; void ZoomInCamera::Tick(){fates::decomp_detail::ZoomInTick(*this);} void ZoomInCamera::Enter(){} void ZoomInCamera::Leave(){}
SubjectCamera::SubjectCamera(const nn::math::VEC3&a,const nn::math::VEC3&b):TransitionCamera(),subject_(a),rotation_(b){fates::decomp_detail::SubjectInitialize(*this,a,b);} SubjectCamera::~SubjectCamera()=default; void SubjectCamera::UpdateParam(){fates::decomp_detail::SubjectUpdateParam(*this);} void SubjectCamera::Tick(){fates::decomp_detail::SubjectTick(*this);} void SubjectCamera::Enter(){fates::decomp_detail::SubjectEnter(*this);} void SubjectCamera::Leave(){fates::decomp_detail::SubjectLeave(*this);} bool SubjectCamera::IsHitPos()const{return true;} bool SubjectCamera::IsHitArea()const{return false;}
WaitingCamera::WaitingCamera():TransitionCamera(){fates::decomp_detail::WaitingInitialize(*this);} WaitingCamera::~WaitingCamera()=default; void WaitingCamera::ChangeCamera(int t,const char*n){requestedType_=t;requestedName_=n;fates::decomp_detail::WaitingChangeCamera(*this,t,n);} void WaitingCamera::Tick(){fates::decomp_detail::WaitingTick(*this);} void WaitingCamera::Enter(){fates::decomp_detail::WaitingEnter(*this);} void WaitingCamera::Leave(){fates::decomp_detail::WaitingLeave(*this);} bool WaitingCamera::CanLookAround()const{return true;}
ComebackCamera::ComebackCamera():TransitionCamera(){fates::decomp_detail::ComebackInitialize(*this);} ComebackCamera::~ComebackCamera()=default; void ComebackCamera::Tick(){fates::decomp_detail::ComebackTick(*this);} void ComebackCamera::Enter(){fates::decomp_detail::ComebackEnter(*this);} void ComebackCamera::Leave(){fates::decomp_detail::ComebackLeave(*this);} bool ComebackCamera::IsHitPos()const{return false;} bool ComebackCamera::IsHitArea()const{return false;}
EncounterCamera::EncounterCamera():TransitionCamera(){fates::decomp_detail::EncounterInitialize(*this);} EncounterCamera::~EncounterCamera()=default; void EncounterCamera::Tick(){fates::decomp_detail::EncounterTick(*this);} void EncounterCamera::Enter(){} void EncounterCamera::Leave(){}
EventBlendCamera::EventBlendCamera(const CameraTrack*t,int frames):EventCamera(t),blendFrames_(frames){fates::decomp_detail::EventBlendInitialize(*this,t,frames);} EventBlendCamera::~EventBlendCamera()=default; void EventBlendCamera::Tick(){fates::decomp_detail::EventBlendTick(*this);}
BossEncounterCamera::BossEncounterCamera():TransitionCamera(){fates::decomp_detail::BossEncounterInitialize(*this);} BossEncounterCamera::~BossEncounterCamera()=default; void BossEncounterCamera::Tick(){fates::decomp_detail::BossEncounterTick(*this);} void BossEncounterCamera::Enter(){} void BossEncounterCamera::Leave(){}
JobIntroStartCamera::JobIntroStartCamera(bool v):TransitionCamera(),variant_(v){fates::decomp_detail::JobIntroStartInitialize(*this,v);} JobIntroStartCamera::~JobIntroStartCamera()=default; void JobIntroStartCamera::Tick(){fates::decomp_detail::JobIntroStartTick(*this);} void JobIntroStartCamera::Enter(){fates::decomp_detail::JobIntroStartEnter(*this);} void JobIntroStartCamera::Leave(){fates::decomp_detail::JobIntroStartLeave(*this);}
SilentComebackCamera::~SilentComebackCamera()=default; void SilentComebackCamera::Enter(){fates::decomp_detail::SilentComebackEnter(*this);}
