#include "fates/coredeep/deeper_core_impl.hpp"
#include <algorithm>

namespace fates::coredeep {
namespace {
constexpr DeepSpec kSpecs[] = {
    {"MapRange__Clamp", 0x004ED860u, "MapRange__Clamp", DeepFamily::FieldGeometry},
    {"MapRange__Reset_2", 0x004ED930u, "MapRange__Reset_2", DeepFamily::FieldGeometry},
    {"HeightData__Clear", 0x0017C584u, "HeightData__Clear", DeepFamily::FieldGeometry},
    {"util__Curve__Accelfloat", 0x0011EF20u, "util__Curve__Accelfloat", DeepFamily::Utility},
    {"util__Curve__Decelfloat", 0x0011EF74u, "util__Curve__Decelfloat", DeepFamily::Utility},
    {"AABB__Add", 0x003CEEC4u, "AABB__Add", DeepFamily::FieldGeometry},
    {"AABB__Add_2", 0x003CEF58u, "AABB__Add_2", DeepFamily::FieldGeometry},
    {"sound__Effector__Effector_2", 0x004327C0u, "sound__Effector__Effector_2", DeepFamily::Audio},
    {"HeightMap__Commit", 0x00500540u, "HeightMap__Commit", DeepFamily::FieldGeometry},
    {"PolyData__GetPos", 0x00546610u, "PolyData__GetPos", DeepFamily::FieldGeometry},
    {"ProcInst__FindNext", 0x0011D318u, "ProcInst__FindNext", DeepFamily::Process},
    {"FieldSound__StartReverb", 0x00176DB4u, "FieldSound__StartReverb", DeepFamily::Utility},
    {"ProcSoundMonitor__GetInstance", 0x001EF078u, "ProcSoundMonitor__GetInstance", DeepFamily::Audio},
    {"TalkCodeDisposerItem__GetColor8", 0x002193C0u, "TalkCodeDisposerItem__GetColor8", DeepFamily::Presentation},
    {"GP__GetFloat", 0x00223E70u, "GP__GetFloat", DeepFamily::ContentState},
    {"map__sound__anonymous_namespace__TSound__SetName", 0x00398BCCu, "map__sound__anonymous_namespace__TSound__SetName", DeepFamily::Audio},
    {"Icon__Anime__anonymous_namespace__GetIndex", 0x003D07E4u, "Icon__Anime__anonymous_namespace__GetIndex", DeepFamily::Presentation},
    {"MapRange__Add", 0x004ED540u, "MapRange__Add", DeepFamily::FieldGeometry},
    {"MapRange__Reset_4", 0x004ED960u, "MapRange__Reset_4", DeepFamily::FieldGeometry},
    {"FieldArea__InvalidateArea", 0x004FE5F4u, "FieldArea__InvalidateArea", DeepFamily::FieldGeometry},
    {"FieldData__LoadField", 0x004FF63Cu, "FieldData__LoadField", DeepFamily::FieldGeometry},
    {"FieldData__LoadParam", 0x004FF7F0u, "FieldData__LoadParam", DeepFamily::FieldGeometry},
    {"HitResult__Reset", 0x00500980u, "HitResult__Reset", DeepFamily::FieldGeometry},
    {"AABB__IsInside", 0x00528D70u, "AABB__IsInside", DeepFamily::FieldGeometry},
    {"PolyData__GetAABB", 0x00546654u, "PolyData__GetAABB", DeepFamily::FieldGeometry},
    {"HeightData__Commit", 0x0017C5B4u, "HeightData__Commit", DeepFamily::FieldGeometry},
    {"HomeButton__SetCallbacks", 0x0017CADCu, "HomeButton__SetCallbacks", DeepFamily::Presentation},
    {"ProcThread__ProcThread", 0x0018D91Cu, "ProcThread__ProcThread", DeepFamily::Process},
    {"MapDataFile__TryRead", 0x0019EC9Cu, "MapDataFile__TryRead", DeepFamily::Core},
    {"SoundHandle__Play", 0x001A5644u, "SoundHandle__Play", DeepFamily::Audio},
    {"ContentsUtil__GetContentID", 0x001AC940u, "ContentsUtil__GetContentID", DeepFamily::ContentState},
    {"ContentsUtil__Mount", 0x001ACE3Cu, "ContentsUtil__Mount", DeepFamily::ContentState},
    {"FieldWeather__Free", 0x001B1CD0u, "FieldWeather__Free", DeepFamily::FieldGeometry},
    {"FieldWeather__Load", 0x001B1CF4u, "FieldWeather__Load", DeepFamily::FieldGeometry},
    {"FieldWeather__Update", 0x001B1E60u, "FieldWeather__Update", DeepFamily::FieldGeometry},
    {"FieldWeather__SetType", 0x001B1E9Cu, "FieldWeather__SetType", DeepFamily::FieldGeometry},
    {"FieldWorldImpl__UpdateColor", 0x001CECECu, "FieldWorldImpl__UpdateColor", DeepFamily::FieldGeometry},
    {"FieldWorldImpl__LoadPlant", 0x001CFBBCu, "FieldWorldImpl__LoadPlant", DeepFamily::FieldGeometry},
    {"FieldWorldImpl__LoadScene", 0x001CFC30u, "FieldWorldImpl__LoadScene", DeepFamily::FieldGeometry},
    {"GameFontHelper__EquipSkill__GetCloseWidth", 0x001D0878u, "GameFontHelper__EquipSkill__GetCloseWidth", DeepFamily::Presentation},
    {"GameFontHelper__Food__GetCloseWidth", 0x001D0A80u, "GameFontHelper__Food__GetCloseWidth", DeepFamily::Presentation},
    {"GameFontHelper__Item__GetWidthForSignal", 0x001D0C74u, "GameFontHelper__Item__GetWidthForSignal", DeepFamily::Presentation},
    {"GameFontHelper__Gemstone__GetCloseWidth", 0x001D127Cu, "GameFontHelper__Gemstone__GetCloseWidth", DeepFamily::Presentation},
    {"FieldWeatherImpl__Draw", 0x001EA8F0u, "FieldWeatherImpl__Draw", DeepFamily::Core},
    {"ProcSoundMonitor__ResetPosition", 0x001EF094u, "ProcSoundMonitor__ResetPosition", DeepFamily::Audio},
    {"SoundDuplicationChecker__Initialize", 0x00220D50u, "SoundDuplicationChecker__Initialize", DeepFamily::Audio},
    {"is__app__movie__MovieThread__SubTitleLeave", 0x002249F4u, "is__app__movie__MovieThread__SubTitleLeave", DeepFamily::Movie},
    {"map__SortiePosition__SetMax", 0x00361610u, "map__SortiePosition__SetMax", DeepFamily::MapUi},
    {"map__Panel__Panel_2", 0x00394998u, "map__Panel__Panel_2", DeepFamily::MapUi},
    {"AABB__Setup", 0x003CEFECu, "AABB__Setup", DeepFamily::FieldGeometry},
    {"AABB__Expand_2", 0x003CF12Cu, "AABB__Expand_2", DeepFamily::FieldGeometry},
    {"AABB__Offset", 0x003CF174u, "AABB__Offset", DeepFamily::FieldGeometry},
    {"AABB__ExpandY", 0x003CF284u, "AABB__ExpandY", DeepFamily::FieldGeometry},
    {"Font__GetMaxHeight", 0x003CFA7Cu, "Font__GetMaxHeight", DeepFamily::Presentation},
    {"game__graphics__SharedTexture__Get", 0x003E77B0u, "game__graphics__SharedTexture__Get", DeepFamily::Presentation},
    {"game__graphics__Window__DrawVariableWindow", 0x003EA928u, "game__graphics__Window__DrawVariableWindow", DeepFamily::Presentation},
    {"game__graphics__Wallpaper__DrawLower", 0x003EBD8Cu, "game__graphics__Wallpaper__DrawLower", DeepFamily::Presentation},
    {"UIFont__SetCurrent", 0x0044C964u, "UIFont__SetCurrent", DeepFamily::Presentation},
    {"UIFont__GetMaxWidth", 0x0044C974u, "UIFont__GetMaxWidth", DeepFamily::Presentation},
    {"UIFont__PopFont", 0x0044D13Cu, "UIFont__PopFont", DeepFamily::Presentation},
    {"UIFont__PushFont", 0x0044D22Cu, "UIFont__PushFont", DeepFamily::Presentation},
    {"castle__JukeBox__GetBgmLabel", 0x00494620u, "castle__JukeBox__GetBgmLabel", DeepFamily::Core},
    {"GfxUtil__GetRotRad", 0x004DA848u, "GfxUtil__GetRotRad", DeepFamily::FieldGeometry},
    {"ColsTree__Cleanup", 0x004E4D54u, "ColsTree__Cleanup", DeepFamily::FieldGeometry},
    {"GameFont__anonymous_namespace__DrawImpl", 0x004E6D94u, "GameFont__anonymous_namespace__DrawImpl", DeepFamily::Presentation},
    {"MapRange__Expand", 0x004EDA0Cu, "MapRange__Expand", DeepFamily::FieldGeometry},
    {"FieldData__Tick", 0x004FF41Cu, "FieldData__Tick", DeepFamily::FieldGeometry},
    {"FieldData__SetName", 0x004FF4ACu, "FieldData__SetName", DeepFamily::FieldGeometry},
    {"HitResult__Move", 0x005008ECu, "HitResult__Move", DeepFamily::FieldGeometry},
    {"FieldParam__GetTimeZone", 0x00506080u, "FieldParam__GetTimeZone", DeepFamily::FieldGeometry},
    {"MapDataFile__GetPartsList", 0x00508740u, "MapDataFile__GetPartsList", DeepFamily::Core},
    {"RandomSound__GetSoundItem", 0x00508AC8u, "RandomSound__GetSoundItem", DeepFamily::Audio},
    {"ShadowActor__GetShadowAABB", 0x00508AD4u, "ShadowActor__GetShadowAABB", DeepFamily::FieldGeometry},
    {"AABB__GetRadius", 0x00528E30u, "AABB__GetRadius", DeepFamily::FieldGeometry},
    {"ISFont__GetGlyphWidth", 0x0053D6CCu, "ISFont__GetGlyphWidth", DeepFamily::Presentation},
    {"ColsTree__GetCurrent", 0x00545540u, "ColsTree__GetCurrent", DeepFamily::FieldGeometry},
    {"ColsTree__CalcHit", 0x00545838u, "ColsTree__CalcHit", DeepFamily::FieldGeometry},
    {"FieldArea__GetNearArea", 0x00547C08u, "FieldArea__GetNearArea", DeepFamily::FieldGeometry},
    {"FieldData__FindObject_4", 0x00548660u, "FieldData__FindObject_4", DeepFamily::FieldGeometry},
    {"HeightMap__CalcHit", 0x0054900Cu, "HeightMap__CalcHit", DeepFamily::FieldGeometry},
};
}
const DeepSpec* GetDeepSpecs() { return kSpecs; }
std::size_t GetDeepSpecCount() { return sizeof(kSpecs)/sizeof(kSpecs[0]); }
const DeepSpec* FindDeepSpec(std::uint32_t retail_address) { const auto* b=kSpecs; const auto* e=kSpecs+GetDeepSpecCount(); const auto it=std::find_if(b,e,[retail_address](const DeepSpec& s){ return s.retail_address==retail_address; }); return it==e?nullptr:it; }
DeepWord InvokeDeep(DeepRuntime& runtime, std::uint32_t retail_address, const DeepWord* args, std::size_t argc) { const DeepSpec* spec=FindDeepSpec(retail_address); if(spec==nullptr || runtime.invoke==nullptr) return 0; return runtime.invoke(runtime.user,*spec,args,argc); }
} // namespace fates::coredeep
